(function () {
  function add(pairs) {
    for (const k in pairs) {
      Internals.strings.en[k] = pairs[k][0];
      Internals.strings.sr[k] = pairs[k][1];
    }
  }
  Internals.addStrings = add;

  add({
    "site.brand": ["The Internals", "The Internals"],
    "site.nav.label": ["Parts of the PC", "Delovi računara"],
    "site.nav.cpu": ["CPU", "CPU"],
    "site.nav.gpu": ["GPU", "GPU"],
    "site.nav.ram": ["RAM", "RAM"],
    "site.nav.storage": ["Storage", "Skladište"],
    "site.nav.board": ["Motherboard", "Matična ploča"],
    "site.nav.psu": ["PSU", "Napajanje"],
    "site.soon": ["soon", "uskoro"],
    "site.lang.label": ["Language", "Jezik"],
    "site.next": ["All parts", "Svi delovi"],
    "site.nextPart": ["Next part", "Sledeći deo"],
    "site.next.cpu": ["The processor that runs every program", "Procesor koji izvršava svaki program"],
    "site.next.gpu": ["Thousands of small cores drawing pixels", "Hiljade malih jezgara crta piksele"],
    "site.next.ram": ["Where running programs live", "Gde žive programi koji rade"],
    "site.next.storage": ["How SSDs keep data without power", "Kako SSD čuva podatke bez struje"],
    "site.next.board": ["The roads between all the parts", "Putevi između svih delova"],
    "site.next.psu": ["Turning wall power into clean 12 V", "Pretvara struju iz zida u stabilnih 12 V"],
    "site.fineprint": ["Figures are typical for current desktop hardware, rounded for learning.",
      "Brojke su tipične za današnji desktop hardver i zaokružene radi lakšeg učenja."]
  });

  add({
    "ui.3d.aria": ["3D model. Drag to rotate; pinch, or use the plus and minus buttons, to zoom.", "3D model. Prevuci da ga okreneš; raširi prste ili koristi dugmad plus i minus za uvećanje."],
    "ui.3d.hint": ["DRAG TO ROTATE", "PREVUCI DA OKRENEŠ"],
    "ui.3d.fallback": ["3D needs WebGL, which is turned off in this browser. The parts are described below.",
      "3D prikaz zahteva WebGL, koji je isključen u ovom pregledaču. Delovi su opisani ispod."],
    "ui.3d.explode": ["Take apart", "Rastavi"],
    "ui.3d.under": ["Show underside", "Prikaži donju stranu"],
    "ui.3d.top": ["Show top", "Prikaži gornju stranu"],
    "ui.3d.reset": ["Reset view", "Vrati prikaz"],
    "ui.3d.zoomIn": ["Zoom in", "Uvećaj"],
    "ui.3d.zoomOut": ["Zoom out", "Umanji"],
    "ui.motion": ["Motion", "Animacije"],
    "ui.prev": ["Back", "Nazad"],
    "ui.next": ["Next", "Dalje"],
    "ui.quiz.eyebrow": ["Check yourself", "Proveri znanje"],
    "ui.quiz.title3": ["Three quick questions", "Tri brza pitanja"],
    "ui.quiz.p": ["Pick an answer to see if you got it.", "Izaberi odgovor i proveri da li je tačan."],
    "ui.quiz.n": ["Question {n} of {total}", "Pitanje {n} od {total}"],
    "ui.quiz.right": ["Correct. {why}", "Tačno. {why}"],
    "ui.quiz.wrong": ["Not quite. Try another answer.", "Nije tačno. Probaj drugi odgovor."]
  });

  add({
    "cpu.eyebrow": ["Part 01 · The processor", "Deo 01 · Procesor"],
    "cpu.full": ["Central Processing Unit", "Centralna procesorska jedinica"],
    "cpu.lede": ["The CPU runs every program on your computer. It fetches an instruction, works out what it means, carries it out and moves to the next, billions of times per second.",
      "Procesor izvršava svaki program na računaru. Uzima instrukciju, utvrđuje šta znači, izvršava je i prelazi na sledeću, i tako milijarde puta u sekundi."],
    "cpu.spec.clock": ["Clock speed", "Radni takt"],
    "cpu.spec.cores": ["Cores", "Jezgra"],
    "cpu.spec.transistors": ["Transistors", "Tranzistori"],
    "cpu.spec.transistors.v": ["~20 billion", "~20 milijardi"],
    "cpu.spec.power": ["Power draw", "Potrošnja"],
    "cpu.fineprint": ["Typical 2025 desktop figures. Drag the model to rotate it and use the slider to take it apart.",
      "Tipične vrednosti za desktop procesor iz 2025. Prevuci model da ga okreneš, a klizačem ga rastavi."],

    "cpu.part.ihs": ["Heat spreader", "Metalni poklopac"],
    "cpu.part.ihs.blurb": ["A nickel-plated copper lid. It spreads heat from the small die over a larger area for the cooler, and protects the silicon.",
      "Poklopac od poniklovanog bakra. Širi toplotu sa malog čipa na veću površinu, odakle je hladnjak odvodi, i štiti silicijum."],
    "cpu.part.ihs.fact": ["Copper conducts heat about 15,000× better than air", "Bakar provodi toplotu oko 15.000 puta bolje od vazduha"],
    "cpu.part.tim": ["Thermal interface", "Termalni sloj"],
    "cpu.part.tim.blurb": ["Solder or thermal paste between the die and the lid. It fills microscopic air gaps, because air blocks heat.",
      "Lem ili termalna pasta između čipa i poklopca. Popunjava mikroskopske šupljine sa vazduhom, jer vazduh loše provodi toplotu."],
    "cpu.part.tim.fact": ["Thinner than a sheet of paper", "Tanji od lista papira"],
    "cpu.part.die": ["Silicon die", "Silicijumski čip"],
    "cpu.part.die.blurb": ["The processor itself: a fingernail-sized slice of silicon holding tens of billions of transistors, built in more than a dozen layers.",
      "Sam procesor: pločica silicijuma veličine nokta sa desetinama milijardi tranzistora, izgrađena u više od deset slojeva."],
    "cpu.part.die.fact": ["~100–250 mm² · a hair is ~70,000 nm thick, transistor features a few nm", "~100–250 mm² · vlas kose je debela ~70.000 nm, detalji tranzistora svega nekoliko nm"],
    "cpu.part.substrate": ["Substrate", "Podloga (supstrat)"],
    "cpu.part.substrate.blurb": ["A small multi-layer circuit board. It fans the die's thousands of tiny connections out to contacts big enough for the socket. The small parts on it are capacitors that keep the power steady.",
      "Mala višeslojna štampana ploča. Hiljade sićušnih veza čipa razvodi do kontakata dovoljno velikih za podnožje. Sitne komponente na njoj su kondenzatori koji stabilizuju napajanje."],
    "cpu.part.substrate.fact": ["About 10 copper layers in ~1 mm", "Oko 10 bakarnih slojeva u ~1 mm"],
    "cpu.part.pads": ["Contact pads", "Kontakti"],
    "cpu.part.pads.blurb": ["Gold-plated pads on the underside. In the socket, each one presses on a spring pin and carries power or data.",
      "Pozlaćeni kontakti na donjoj strani. U podnožju svaki pritiska jednu opružnu iglicu i prenosi napajanje ili podatke."],
    "cpu.part.pads.fact": ["~1,700 contacts on current desktop sockets", "~1.700 kontakata na današnjim desktop podnožjima"]
  });

  add({
    "cpu.sw.eyebrow": ["Chapter 1 · Transistors", "Poglavlje 1 · Tranzistori"],
    "cpu.sw.title": ["It is all switches", "Sve su to prekidači"],
    "cpu.sw.p1": ["A <strong>transistor</strong> is a switch with no moving parts. Voltage on the <strong>gate</strong> lets current flow; no voltage, no current. Current means <strong>1</strong>, no current means <strong>0</strong>.",
      "<strong>Tranzistor</strong> je prekidač bez pokretnih delova. Napon na <strong>gejtu</strong> pušta struju da teče; bez napona nema struje. Struja znači <strong>1</strong>, bez struje <strong>0</strong>."],
    "cpu.sw.p2": ["Two switches in a row pass current only when both are on. That is an <strong>AND gate</strong>, a basic building block of digital logic.",
      "Dva prekidača u nizu propuštaju struju samo kada su oba uključena. To je <strong>I kolo</strong> (AND), osnovni gradivni blok digitalne logike."],
    "cpu.sw.mosfet.aria": ["Cross-section of a transistor", "Presek tranzistora"],
    "cpu.sw.and.aria": ["Two switches in series forming an AND gate", "Dva prekidača u nizu čine I kolo"],
    "cpu.sw.base": ["SILICON BASE", "SILICIJUMSKA OSNOVA"],
    "cpu.sw.source": ["SOURCE", "SORS"],
    "cpu.sw.drain": ["DRAIN", "DREJN"],
    "cpu.sw.insulator": ["INSULATOR", "IZOLATOR"],
    "cpu.sw.gate": ["GATE", "GEJT"],
    "cpu.sw.output": ["OUTPUT", "IZLAZ"],
    "cpu.sw.battery": ["BATTERY", "BATERIJA"],
    "cpu.sw.lamp": ["LAMP = OUTPUT", "SIJALICA = IZLAZ"],
    "cpu.sw.caption": ["Current flows only when A and B are both closed.", "Struja teče samo kada su i A i B zatvoreni."],
    "cpu.sw.gateOn": ["Gate voltage: on", "Napon na gejtu: uključen"],
    "cpu.sw.gateOff": ["Gate voltage: off", "Napon na gejtu: isključen"],
    "cpu.sw.inA": ["Input A: {v}", "Ulaz A: {v}"],
    "cpu.sw.inB": ["Input B: {v}", "Ulaz B: {v}"],
    "cpu.sw.and": ["{a} AND {b} = {o}", "{a} I {b} = {o}"]
  });

  add({
    "cpu.die.eyebrow": ["Chapter 2 · The floorplan", "Poglavlje 2 · Raspored"],
    "cpu.die.title": ["Inside the die", "Unutar čipa"],
    "cpu.die.p": ["The die is divided into areas with different jobs. This map is simplified from a typical 8-core desktop chip. Pick an area.",
      "Čip je podeljen na oblasti sa različitim zadacima. Ova mapa je pojednostavljen prikaz tipičnog desktop čipa sa 8 jezgara. Izaberi oblast."],
    "cpu.die.aria": ["Map of a CPU die", "Mapa procesorskog čipa"],
    "cpu.die.scale": ["≈ 12 mm across, about the size of a fingernail", "≈ 12 mm, otprilike veličine nokta"],
    "cpu.die.coreN": ["CORE {n}", "JEZGRO {n}"],
    "cpu.die.core": ["CPU cores", "Procesorska jezgra"],
    "cpu.die.core.short": ["CORE", "JEZGRO"],
    "cpu.die.core.blurb": ["Each core is a complete processor running its own stream of instructions. Inside are a control unit, arithmetic units, and small, fast L1 and L2 caches.",
      "Svako jezgro je potpun procesor koji izvršava sopstveni niz instrukcija. Unutra su upravljačka jedinica, aritmetičke jedinice i male, brze L1 i L2 keš memorije."],
    "cpu.die.core.fact": ["8 cores · 48 KB L1 + 2 MB L2 each", "8 jezgara · po 48 KB L1 + 2 MB L2"],
    "cpu.die.l3": ["L3 cache", "L3 keš"],
    "cpu.die.l3.short": ["L3 CACHE", "L3 KEŠ"],
    "cpu.die.l3.blurb": ["Fast memory shared by all cores. It keeps recently used data so it does not have to come from slower RAM again. Its regular grid of memory cells is easy to spot in real die photos.",
      "Brza memorija koju dele sva jezgra. Čuva nedavno korišćene podatke da ne bi morali ponovo da se čitaju iz sporijeg RAM-a. Njena pravilna mreža memorijskih ćelija lako se uočava na fotografijama čipa."],
    "cpu.die.l3.fact": ["36 MB shared · ~8× quicker to reach than RAM", "36 MB zajedničke · ~8 puta brža od RAM-a"],
    "cpu.die.gpu": ["Integrated graphics", "Integrisana grafika"],
    "cpu.die.gpu.short": ["GRAPHICS", "GRAFIKA"],
    "cpu.die.gpu.blurb": ["A small graphics processor inside the CPU. Enough for the desktop, video and light games. Gaming PCs add a separate graphics card.",
      "Mali grafički procesor unutar CPU-a. Dovoljan za radnu površinu, video i lakše igre. Računari za igranje imaju i posebnu grafičku karticu."],
    "cpu.die.gpu.fact": ["Many simple cores working on pixels in parallel", "Mnogo jednostavnih jezgara paralelno obrađuje piksele"],
    "cpu.die.mem": ["Memory controller", "Memorijski kontroler"],
    "cpu.die.mem.short": ["MEMORY CTRL", "MEM. KONTROLER"],
    "cpu.die.mem.blurb": ["Handles the link to the RAM sticks. Any data not found in a cache is requested through here.",
      "Upravlja vezom sa RAM modulima. Svaki podatak koji nije u kešu traži se preko njega."],
    "cpu.die.mem.fact": ["2 channels of DDR5 · up to ~90 GB/s", "2 DDR5 kanala · do ~90 GB/s"],
    "cpu.die.io": ["I/O and PCIe", "U/I i PCIe"],
    "cpu.die.io.short": ["I/O · PCIe", "U/I · PCIe"],
    "cpu.die.io.blurb": ["Links to the rest of the PC: the graphics card and SSDs over PCI Express, the display outputs, and the motherboard chipset for USB and networking.",
      "Veze sa ostatkom računara: grafička kartica i SSD-ovi preko PCI Express-a, video izlazi i čipset matične ploče za USB i mrežu."],
    "cpu.die.io.fact": ["~24 PCIe 5.0 lanes", "~24 PCIe 5.0 linije"]
  });

  add({
    "cpu.sim.eyebrow": ["Chapter 3 · Running a program", "Poglavlje 3 · Izvršavanje programa"],
    "cpu.sim.title": ["Fetch, decode, execute", "Pribavi, dekodiraj, izvrši"],
    "cpu.sim.p1": ["A program is a list of small instructions stored in memory. For each one the CPU does three steps: <strong>fetch</strong> it, <strong>decode</strong> it, <strong>execute</strong> it.",
      "Program je niz malih instrukcija u memoriji. Za svaku procesor radi tri koraka: <strong>pribavlja</strong> je, <strong>dekodira</strong> i <strong>izvršava</strong>."],
    "cpu.sim.p2": ["This program adds 7 and 5. Step through it and watch the numbers move.",
      "Ovaj program sabira 7 i 5. Prođi kroz njega korak po korak i prati kako se brojevi kreću."],
    "cpu.sim.aria": ["Animated model of a CPU running a program", "Animirani model procesora koji izvršava program"],
    "cpu.sim.ph.fetch": ["Fetch", "Pribavljanje"],
    "cpu.sim.ph.decode": ["Decode", "Dekodiranje"],
    "cpu.sim.ph.execute": ["Execute", "Izvršavanje"],
    "cpu.sim.ready": ["Ready", "Spremno"],
    "cpu.sim.readyText": ["The Program Counter starts at address 0, where the first instruction is. Press Step.",
      "Programski brojač počinje od adrese 0, gde je prva instrukcija. Pritisni Korak."],
    "cpu.sim.step": ["Step", "Korak"],
    "cpu.sim.play": ["Play all", "Pusti sve"],
    "cpu.sim.playing": ["Playing…", "Pušta se…"],
    "cpu.sim.reset": ["Reset", "Ispočetka"],
    "cpu.sim.count": ["Step {n} of {total}", "Korak {n} od {total}"],
    "cpu.sim.cpu": ["CPU", "PROCESOR"],
    "cpu.sim.cu": ["CONTROL UNIT", "UPRAVLJAČKA JEDINICA"],
    "cpu.sim.pc": ["PROGRAM COUNTER", "PROGRAMSKI BROJAČ"],
    "cpu.sim.ir": ["INSTRUCTION REGISTER", "REGISTAR INSTRUKCIJA"],
    "cpu.sim.regs": ["REGISTERS", "REGISTRI"],
    "cpu.sim.alu": ["ARITHMETIC LOGIC UNIT", "ARITMETIČKO-LOGIČKA JEDINICA"],
    "cpu.sim.bus": ["SYSTEM BUS", "SISTEMSKA MAGISTRALA"],
    "cpu.sim.ram": ["RAM", "RAM"],
    "cpu.sim.ramNote": ["0–4 PROGRAM · 5–7 DATA", "0–4 PROGRAM · 5–7 PODACI"],
    "cpu.sim.addr": ["addr {n}", "adr {n}"],
    "cpu.sim.note0": ["copy address 6 into R1", "kopiraj adresu 6 u R1"],
    "cpu.sim.note1": ["copy address 7 into R2", "kopiraj adresu 7 u R2"],
    "cpu.sim.note2": ["add R1 and R2, answer into R3", "saberi R1 i R2, rezultat u R3"],
    "cpu.sim.note3": ["save R3 to address 5", "sačuvaj R3 na adresu 5"],
    "cpu.sim.note4": ["stop", "kraj"],
    "cpu.sim.fetch": ["The Program Counter holds {i}, so address {i} goes over the bus to RAM. The instruction stored there comes back into the Instruction Register, and the counter moves on to {n}.",
      "Programski brojač sadrži {i}, pa adresa {i} ide magistralom do RAM-a. Instrukcija sa te adrese vraća se u registar instrukcija, a brojač prelazi na {n}."],
    "cpu.sim.dec0": ["LOAD copies a number from memory into a register: take what is at address 6 and put it in R1.",
      "LOAD kopira broj iz memorije u registar: uzmi ono što je na adresi 6 i stavi u R1."],
    "cpu.sim.dec1": ["Another LOAD: address 7 into R2.", "Još jedan LOAD: adresa 7 u R2."],
    "cpu.sim.dec2": ["ADD: the control unit sets the ALU to add R1 and R2 and send the result to R3.",
      "ADD: upravljačka jedinica podešava ALU da sabere R1 i R2 i rezultat pošalje u R3."],
    "cpu.sim.dec3": ["STORE is the reverse of LOAD: copy R3 out to address 5.", "STORE je suprotno od LOAD: kopiraj R3 na adresu 5."],
    "cpu.sim.dec4": ["HALT: nothing left to do.", "HALT: nema više posla."],
    "cpu.sim.ex0": ["Address 6 goes to RAM, and the number 7 comes back into R1.", "Adresa 6 ide do RAM-a, a broj 7 se vraća u R1."],
    "cpu.sim.ex1": ["Address 7 goes out, and 5 comes back into R2.", "Adresa 7 ide do RAM-a, a broj 5 se vraća u R2."],
    "cpu.sim.ex2": ["Both numbers enter the ALU, which adds them in one cycle. The result, 12, goes to R3.",
      "Oba broja ulaze u ALU, koja ih sabira u jednom ciklusu. Rezultat 12 ide u R3."],
    "cpu.sim.ex3": ["12 travels over the bus into RAM at address 5. The answer is saved.",
      "Broj 12 putuje magistralom u RAM na adresu 5. Rezultat je sačuvan."],
    "cpu.sim.ex4": ["Done: 7 + 5 = 12, stored at address 5. A real CPU does all 15 steps in a few billionths of a second.",
      "Gotovo: 7 + 5 = 12, sačuvano na adresi 5. Pravi procesor svih 15 koraka obavi za nekoliko milijarditih delova sekunde."]
  });

  add({
    "cpu.clk.eyebrow": ["Chapter 4 · Speed", "Poglavlje 4 · Brzina"],
    "cpu.clk.title": ["The clock and the pipeline", "Takt i protočna obrada"],
    "cpu.clk.p": ["Every part of the CPU moves in step with a <strong>clock</strong> signal. Each tick is one <strong>cycle</strong>, and a 5 GHz chip gets five billion of them per second.",
      "Svi delovi procesora rade u ritmu <strong>takta</strong>. Svaki otkucaj je jedan <strong>ciklus</strong>, a čip od 5 GHz ima pet milijardi ciklusa u sekundi."],
    "cpu.clk.aria": ["Animated clock signal", "Animirani signal takta"],
    "cpu.clk.label": ["Clock", "Takt"],
    "cpu.clk.read": ["{c} cycles per second · one cycle lasts {ns} ns · light travels only {cm} cm in that time",
      "{c} ciklusa u sekundi · jedan ciklus traje {ns} ns · svetlost za to vreme pređe samo {cm} cm"],
    "cpu.clk.high": ["HIGH (1)", "VISOK (1)"],
    "cpu.clk.low": ["LOW (0)", "NIZAK (0)"],
    "cpu.clk.cycle": ["1 cycle", "1 ciklus"],
    "cpu.pipe.title": ["Pipelining: overlapping the steps", "Protočna obrada: koraci se preklapaju"],
    "cpu.pipe.p": ["Instead of finishing one instruction before starting the next, the CPU works like an assembly line. While one instruction executes, the next is decoded and the one after is fetched.",
      "Umesto da završi jednu instrukciju pa tek onda počne sledeću, procesor radi kao pokretna traka. Dok se jedna instrukcija izvršava, sledeća se dekodira, a naredna pribavlja."],
    "cpu.pipe.on": ["Pipelining: on", "Protočna obrada: uključena"],
    "cpu.pipe.off": ["Pipelining: off", "Protočna obrada: isključena"],
    "cpu.pipe.run": ["Run 6 instructions", "Pokreni 6 instrukcija"],
    "cpu.pipe.cycles": ["cycles", "ciklusa"],
    "cpu.pipe.ipc": ["instructions / cycle", "instrukcija po ciklusu"],
    "cpu.pipe.cycle": ["cycle", "ciklus"],
    "cpu.pipe.instr": ["instruction {n}", "instrukcija {n}"],
    "cpu.pipe.F": ["F", "P"], "cpu.pipe.F.name": ["Fetch", "Pribavljanje"],
    "cpu.pipe.D": ["D", "D"], "cpu.pipe.D.name": ["Decode", "Dekodiranje"],
    "cpu.pipe.E": ["E", "I"], "cpu.pipe.E.name": ["Execute", "Izvršavanje"],
    "cpu.pipe.W": ["W", "U"], "cpu.pipe.W.name": ["Write result", "Upis rezultata"]
  });

  add({
    "cpu.mem.eyebrow": ["Chapter 5 · Memory", "Poglavlje 5 · Memorija"],
    "cpu.mem.title": ["Why caches exist", "Zašto postoji keš"],
    "cpu.mem.p1": ["An addition takes one cycle, but reading from RAM takes hundreds. So the CPU keeps copies of recent data in small, fast <strong>caches</strong> close to each core. Smaller and closer means faster.",
      "Sabiranje traje jedan ciklus, a čitanje iz RAM-a stotine. Zato procesor čuva kopije skorašnjih podataka u malim, brzim <strong>keš memorijama</strong> blizu jezgara. Manje i bliže znači brže."],
    "cpu.mem.p2": ["The right-hand column stretches one cycle to one second.", "Desna kolona rasteže jedan ciklus na jednu sekundu."],
    "cpu.mem.race": ["Race a request to each level", "Pošalji zahtev na svaki nivo"],
    "cpu.mem.log": ["Log scale: each step is 10× slower", "Logaritamska skala: svaki korak je 10 puta sporiji"],
    "cpu.mem.cycle.one": ["{n} cycle", "{n} ciklus"],
    "cpu.mem.cycle.other": ["{n} cycles", "{n} ciklusa"],
    "cpu.mem.reg": ["Registers", "Registri"], "cpu.mem.reg.sub": ["~1 KB, inside the core", "~1 KB, unutar jezgra"], "cpu.mem.reg.h": ["1 second", "1 sekunda"],
    "cpu.mem.l1": ["L1 cache", "L1 keš"], "cpu.mem.l1.sub": ["48 KB per core", "48 KB po jezgru"], "cpu.mem.l1.h": ["5 seconds", "5 sekundi"],
    "cpu.mem.l2": ["L2 cache", "L2 keš"], "cpu.mem.l2.sub": ["2 MB per core", "2 MB po jezgru"], "cpu.mem.l2.h": ["15 seconds", "15 sekundi"],
    "cpu.mem.l3": ["L3 cache", "L3 keš"], "cpu.mem.l3.sub": ["36 MB, shared", "36 MB, zajednički"], "cpu.mem.l3.h": ["50 seconds", "50 sekundi"],
    "cpu.mem.ram": ["RAM", "RAM"], "cpu.mem.ram.sub": ["16–64 GB, on the motherboard", "16–64 GB, na matičnoj ploči"], "cpu.mem.ram.h": ["7 minutes", "7 minuta"],
    "cpu.mem.ssd": ["SSD", "SSD"], "cpu.mem.ssd.sub": ["1–4 TB, storage", "1–4 TB, skladište"], "cpu.mem.ssd.h": ["4.6 days", "4,6 dana"]
  });

  add({
    "cpu.cores.eyebrow": ["Chapter 6 · Parallelism", "Poglavlje 6 · Paralelizam"],
    "cpu.cores.title": ["More cores, more work", "Više jezgara, više posla"],
    "cpu.cores.p1": ["Around 2005 clock speeds stopped rising because faster chips ran too hot, so designers added cores instead. A job that splits into independent pieces spreads across all of them.",
      "Oko 2005. takt je prestao da raste jer su brži čipovi previše grejali, pa su proizvođači počeli da dodaju jezgra. Posao koji se deli na nezavisne delove raspoređuje se na sva jezgra."],
    "cpu.cores.p2": ["Most jobs also have a part that <strong>cannot be split</strong>. It runs on one core however many you have, and that limits the speed-up.",
      "Većina poslova ima i deo koji <strong>ne može da se podeli</strong>. On se izvršava na jednom jezgru bez obzira na broj jezgara, i to ograničava ubrzanje."],
    "cpu.cores.group": ["Number of cores", "Broj jezgara"],
    "cpu.cores.n.one": ["{n} core", "{n} jezgro"],
    "cpu.cores.n.few": ["{n} cores", "{n} jezgra"],
    "cpu.cores.n.other": ["{n} cores", "{n} jezgara"],
    "cpu.cores.serialOn": ["Unsplittable part: on", "Nedeljivi deo: uključen"],
    "cpu.cores.serialOff": ["Unsplittable part: off", "Nedeljivi deo: isključen"],
    "cpu.cores.run": ["Run job", "Pokreni posao"],
    "cpu.cores.lane": ["core {n}", "jezgro {n}"],
    "cpu.cores.running": ["Running…", "Radi…"],
    "cpu.cores.read": ["Finishes in {t} time units · {x}× faster than 1 core", "Završava za {t} jedinica vremena · {x} puta brže od 1 jezgra"]
  });

  add({
    "cpu.quiz.eyebrow": ["Check yourself", "Proveri znanje"],
    "cpu.quiz.title": ["Four quick questions", "Četiri brza pitanja"],
    "cpu.quiz.p": ["Pick an answer to see if you got it.", "Izaberi odgovor i proveri da li je tačan."],
    "cpu.quiz.n": ["Question {n} of {total}", "Pitanje {n} od {total}"],
    "cpu.quiz.right": ["Correct. {why}", "Tačno. {why}"],
    "cpu.quiz.wrong": ["Not quite. Try another answer.", "Nije tačno. Probaj drugi odgovor."],
    "cpu.quiz.q1": ["What is the metal lid on a CPU for?", "Čemu služi metalni poklopac na procesoru?"],
    "cpu.quiz.q1.a0": ["Spreading heat to the cooler", "Širi toplotu ka hladnjaku"],
    "cpu.quiz.q1.a1": ["Storing data when the power is off", "Čuva podatke kad je struja isključena"],
    "cpu.quiz.q1.a2": ["Connecting the CPU to the RAM", "Povezuje procesor sa RAM-om"],
    "cpu.quiz.q1.why": ["The die is tiny, so the lid spreads its heat over a bigger area for the cooler.",
      "Čip je sićušan, pa poklopac širi njegovu toplotu na veću površinu za hladnjak."],
    "cpu.quiz.q2": ["How many cycles per second does a 4 GHz CPU get?", "Koliko ciklusa u sekundi ima procesor od 4 GHz?"],
    "cpu.quiz.q2.a0": ["4 thousand", "4 hiljade"],
    "cpu.quiz.q2.a1": ["4 million", "4 miliona"],
    "cpu.quiz.q2.a2": ["4 billion", "4 milijarde"],
    "cpu.quiz.q2.why": ["Giga means billion, so that is 4,000,000,000 cycles per second.", "Giga znači milijarda, dakle 4.000.000.000 ciklusa u sekundi."],
    "cpu.quiz.q3": ["Why does a CPU have cache memory?", "Zašto procesor ima keš memoriju?"],
    "cpu.quiz.q3.a0": ["RAM is too small to hold programs", "RAM je premali za programe"],
    "cpu.quiz.q3.a1": ["RAM takes hundreds of cycles, so recent data is kept closer", "RAM-u treba stotine ciklusa, pa se skorašnji podaci drže bliže"],
    "cpu.quiz.q3.a2": ["Cache saves your files when the PC is off", "Keš čuva fajlove kad je računar ugašen"],
    "cpu.quiz.q3.why": ["L1 answers in about 5 cycles, RAM in about 400. Keeping data close means less waiting.",
      "L1 odgovara za oko 5 ciklusa, RAM za oko 400. Podaci blizu jezgra znače manje čekanja."],
    "cpu.quiz.q4": ["Part of a job cannot be split. You go from 4 to 8 cores. How much faster is it?",
      "Deo posla ne može da se podeli. Sa 4 prelaziš na 8 jezgara. Koliko je brže?"],
    "cpu.quiz.q4.a0": ["Exactly twice as fast", "Tačno duplo brže"],
    "cpu.quiz.q4.a1": ["Less than twice as fast", "Manje nego duplo brže"],
    "cpu.quiz.q4.a2": ["No faster at all", "Nimalo brže"],
    "cpu.quiz.q4.why": ["Only the splittable part speeds up. The rest takes the same time on any number of cores.",
      "Ubrzava se samo deljivi deo. Ostatak traje isto bez obzira na broj jezgara."]
  });

  add({
    "gpu.eyebrow": ["Part 02 · The graphics card", "Deo 02 · Grafička kartica"],
    "gpu.full": ["Graphics Processing Unit", "Grafička procesorska jedinica"],
    "gpu.lede": ["The GPU draws everything you see. A CPU has a few powerful cores; a GPU has thousands of simple ones that work on millions of pixels at the same time.",
      "GPU crta sve što vidiš na ekranu. CPU ima nekoliko snažnih jezgara, a GPU hiljade jednostavnih koja istovremeno obrađuju milione piksela."],
    "gpu.spec.cores": ["Shader cores", "Šejder jezgra"], "gpu.spec.cores.v": ["2,000–16,000", "2.000–16.000"],
    "gpu.spec.vram": ["Video memory", "Video memorija"], "gpu.spec.vram.v": ["8–24 GB", "8–24 GB"],
    "gpu.spec.bw": ["Memory speed", "Brzina memorije"], "gpu.spec.bw.v": ["up to ~1 TB/s", "do ~1 TB/s"],
    "gpu.spec.power": ["Power draw", "Potrošnja"], "gpu.spec.power.v": ["100–450 W", "100–450 W"],
    "gpu.fineprint": ["Typical 2025 graphics cards. Drag to rotate, slide to take it apart.",
      "Tipične grafičke kartice iz 2025. Prevuci da okreneš, a klizačem rastavi."],

    "gpu.part.shroud": ["Fans and shroud", "Ventilatori i maska"],
    "gpu.part.shroud.blurb": ["Two or three fans push air through the heatsink. The plastic shroud holds them and guides the air.",
      "Dva ili tri ventilatora duvaju vazduh kroz hladnjak. Plastična maska ih drži i usmerava vazduh."],
    "gpu.part.shroud.fact": ["Many cards stop their fans at idle to stay silent", "Mnoge kartice gase ventilatore kad miruju, radi tišine"],
    "gpu.part.cooler": ["Heatsink and heat pipes", "Hladnjak i toplotne cevi"],
    "gpu.part.cooler.blurb": ["Copper heat pipes carry heat from the chip into hundreds of thin aluminium fins, where the fans' air takes it away.",
      "Bakarne toplotne cevi odvode toplotu sa čipa u stotine tankih aluminijumskih rebara, odakle je vazduh ventilatora odnosi."],
    "gpu.part.cooler.fact": ["A high-end card turns 300–450 W into heat", "Jača kartica pretvara 300–450 W u toplotu"],
    "gpu.part.gpu": ["GPU chip", "Grafički čip"],
    "gpu.part.gpu.blurb": ["The graphics processor itself: thousands of small cores that work on many pixels at once.",
      "Sam grafički procesor: hiljade malih jezgara koja rade na mnogo piksela odjednom."],
    "gpu.part.gpu.fact": ["Up to ~16,000 shader cores and ~75 billion transistors", "Do ~16.000 šejder jezgara i ~75 milijardi tranzistora"],
    "gpu.part.vram": ["Video memory (VRAM)", "Video memorija (VRAM)"],
    "gpu.part.vram.blurb": ["Fast memory chips placed right around the GPU. They hold textures, 3D models and the frames being drawn.",
      "Brzi memorijski čipovi odmah oko GPU-a. U njima su teksture, 3D modeli i slike koje se crtaju."],
    "gpu.part.vram.fact": ["8–24 GB of GDDR6 or GDDR7", "8–24 GB GDDR6 ili GDDR7 memorije"],
    "gpu.part.pcb": ["Circuit board", "Štampana ploča"],
    "gpu.part.pcb.blurb": ["Connects everything: the power stages that feed the GPU, the PCIe connector that plugs into the motherboard, and the display outputs.",
      "Povezuje sve: stepene napajanja za GPU, PCIe konektor koji ide u matičnu ploču i video izlaze."],
    "gpu.part.pcb.fact": ["PCIe x16: 16 data lanes to the CPU", "PCIe x16: 16 linija podataka do procesora"],
    "gpu.part.backplate": ["Backplate", "Zadnja ploča"],
    "gpu.part.backplate.blurb": ["A metal plate on the back. It stiffens the long, heavy card so it does not bend, and spreads a little heat.",
      "Metalna ploča sa zadnje strane. Ukrućuje dugačku, tešku karticu da se ne savija i odvodi malo toplote."],
    "gpu.part.backplate.fact": ["Big cards are over 30 cm long and weigh 2 kg", "Velike kartice su duže od 30 cm i teške 2 kg"],

    "gpu.par.eyebrow": ["Chapter 1 · Parallel work", "Poglavlje 1 · Paralelni rad"],
    "gpu.par.title": ["Many small cores", "Mnogo malih jezgara"],
    "gpu.par.p1": ["Every pixel needs its colour worked out, and a 1440p screen has 3.7 million of them, 60 or more times a second. Each pixel's maths is simple and independent, so a GPU does thousands at once.",
      "Za svaki piksel treba izračunati boju, a ekran od 1440p ima 3,7 miliona piksela, 60 ili više puta u sekundi. Račun za svaki piksel je jednostavan i nezavisan, pa ih GPU radi na hiljade odjednom."],
    "gpu.par.p2": ["Race both chips on the same image.", "Pokreni trku oba čipa na istoj slici."],
    "gpu.par.cpu": ["CPU · 8 fast cores", "CPU · 8 brzih jezgara"],
    "gpu.par.gpu": ["GPU · 256 simple cores (real ones have thousands)", "GPU · 256 jednostavnih jezgara (pravi ih ima hiljade)"],
    "gpu.par.run": ["Draw the image", "Nacrtaj sliku"],
    "gpu.par.time": ["{p}% · {s} s", "{p}% · {s} s"],
    "gpu.par.note": ["Each GPU core is slower, but 256 of them finish long before 8 fast ones.",
      "Svako GPU jezgro je sporije, ali 256 njih završi mnogo pre 8 brzih."],

    "gpu.pipe.eyebrow": ["Chapter 2 · The graphics pipeline", "Poglavlje 2 · Grafički protok"],
    "gpu.pipe.title": ["From triangles to pixels", "Od trouglova do piksela"],
    "gpu.pipe.p": ["Every 3D object in a game is built from triangles. For each frame the GPU turns them into coloured pixels in four main steps.",
      "Svaki 3D objekat u igri sastoji se od trouglova. Za svaki frejm GPU ih u četiri glavna koraka pretvara u obojene piksele."],
    "gpu.pipe.aria": ["The graphics pipeline turning triangles into pixels", "Grafički protok pretvara trouglove u piksele"],
    "gpu.pipe.s0": ["{n} Vertices", "{n} Temena"],
    "gpu.pipe.s1": ["{n} Triangles", "{n} Trouglovi"],
    "gpu.pipe.s2": ["{n} Rasterise", "{n} Rasterizacija"],
    "gpu.pipe.s3": ["{n} Shade", "{n} Senčenje"],
    "gpu.pipe.t0": ["A 3D model is a list of corner points called vertices. The GPU moves each one to its place on the screen, based on where the camera is.",
      "3D model je spisak tačaka koje se zovu temena. GPU svako teme premešta na njegovo mesto na ekranu, u zavisnosti od položaja kamere."],
    "gpu.pipe.t1": ["The points are joined into triangles. Any shape, from a character's face to a whole city, is made of them.",
      "Tačke se spajaju u trouglove. Svaki oblik, od lica lika do celog grada, sastoji se od njih."],
    "gpu.pipe.t2": ["Rasterisation: the GPU works out which pixels each triangle covers. Now it knows which pixels need a colour.",
      "Rasterizacija: GPU određuje koje piksele pokriva svaki trougao. Sada zna koje piksele treba obojiti."],
    "gpu.pipe.t3": ["A small program called a shader runs once for every covered pixel and picks its colour from light, textures and shadows. Thousands of shaders run at the same time.",
      "Mali program koji se zove šejder pokreće se za svaki pokriveni piksel i bira boju na osnovu svetla, tekstura i senki. Hiljade šejdera rade istovremeno."],

    "gpu.fps.eyebrow": ["Chapter 3 · Frame rate", "Poglavlje 3 · Broj frejmova"],
    "gpu.fps.title": ["Frames per second", "Frejmovi u sekundi"],
    "gpu.fps.p": ["Motion on screen is a quick series of still images called frames. More frames per second looks smoother, but gives the GPU less time to draw each one.",
      "Pokret na ekranu je brz niz mirnih slika koje se zovu frejmovi. Više frejmova u sekundi izgleda glađe, ali GPU ima manje vremena da nacrta svaki."],
    "gpu.fps.aria": ["The same motion at 30, 60 and 144 frames per second", "Isti pokret pri 30, 60 i 144 frejma u sekundi"],
    "gpu.fps.lane": ["{f} FPS · {ms} ms per frame", "{f} FPS · {ms} ms po frejmu"],
    "gpu.fps.note": ["Faint dots show the last few frames. Fewer frames means bigger jumps between them.",
      "Blede tačke pokazuju poslednjih nekoliko frejmova. Manje frejmova znači veće skokove između njih."],

    "gpu.quiz.q1": ["Why does a GPU have thousands of cores?", "Zašto GPU ima hiljade jezgara?"],
    "gpu.quiz.q1.a0": ["Pixels can be worked out independently, so many run at once", "Pikseli se računaju nezavisno, pa mnogo njih može odjednom"],
    "gpu.quiz.q1.a1": ["Each GPU core is faster than a CPU core", "Svako GPU jezgro je brže od CPU jezgra"],
    "gpu.quiz.q1.a2": ["To store more textures", "Da bi čuvao više tekstura"],
    "gpu.quiz.q1.why": ["No pixel's colour depends on its neighbours, so the work splits across many simple cores.",
      "Boja jednog piksela ne zavisi od suseda, pa se posao deli na mnogo jednostavnih jezgara."],
    "gpu.quiz.q2": ["What is VRAM for?", "Čemu služi VRAM?"],
    "gpu.quiz.q2.a0": ["Storing the operating system", "Čuvanju operativnog sistema"],
    "gpu.quiz.q2.a1": ["Holding textures, models and frames for the GPU", "Čuvanju tekstura, modela i frejmova za GPU"],
    "gpu.quiz.q2.a2": ["Cooling the GPU chip", "Hlađenju grafičkog čipa"],
    "gpu.quiz.q2.why": ["VRAM sits right next to the GPU so it can reach that data very quickly.",
      "VRAM je odmah pored GPU-a, pa GPU veoma brzo dolazi do tih podataka."],
    "gpu.quiz.q3": ["At 60 FPS, how long does the GPU have to draw each frame?", "Pri 60 FPS, koliko vremena GPU ima za jedan frejm?"],
    "gpu.quiz.q3.a0": ["About 1.7 ms", "Oko 1,7 ms"],
    "gpu.quiz.q3.a1": ["About 16.7 ms", "Oko 16,7 ms"],
    "gpu.quiz.q3.a2": ["About 60 ms", "Oko 60 ms"],
    "gpu.quiz.q3.why": ["1,000 ms ÷ 60 frames ≈ 16.7 ms for each frame.", "1.000 ms ÷ 60 frejmova ≈ 16,7 ms za svaki frejm."]
  });

  add({
    "ram.eyebrow": ["Part 03 · Memory", "Deo 03 · Memorija"],
    "ram.full": ["Random Access Memory", "Memorija sa nasumičnim pristupom"],
    "ram.lede": ["RAM holds the programs and data you are using right now, so the CPU can reach them fast. It is far quicker than an SSD, but it forgets everything when the power goes off.",
      "RAM čuva programe i podatke koje trenutno koristiš, da bi im procesor brzo pristupio. Mnogo je brži od SSD-a, ali sve zaboravi kad nestane struje."],
    "ram.spec.cap": ["Capacity", "Kapacitet"], "ram.spec.cap.v": ["16–64 GB", "16–64 GB"],
    "ram.spec.rate": ["Transfer rate", "Brzina prenosa"], "ram.spec.rate.v": ["6,000 MT/s", "6.000 MT/s"],
    "ram.spec.bw": ["Bandwidth", "Propusni opseg"], "ram.spec.bw.v": ["~96 GB/s", "~96 GB/s"],
    "ram.spec.lat": ["Latency", "Kašnjenje"], "ram.spec.lat.v": ["~80 ns", "~80 ns"],
    "ram.fineprint": ["Typical 2025 DDR5 desktop memory, two sticks. Drag to rotate, slide to take it apart.",
      "Tipična DDR5 desktop memorija iz 2025, dva modula. Prevuci da okreneš, a klizačem rastavi."],

    "ram.part.heatspreader": ["Heat spreader", "Hladnjak"],
    "ram.part.heatspreader.blurb": ["An aluminium cover that spreads heat away from the chips. Fast memory runs warm, and the cover also protects it.",
      "Aluminijumski omotač koji širi toplotu sa čipova. Brza memorija se greje, a omotač je i štiti."],
    "ram.part.heatspreader.fact": ["Mostly found on fast or overclocked sticks", "Uglavnom na brzim ili overklokovanim modulima"],
    "ram.part.chips": ["Memory chips", "Memorijski čipovi"],
    "ram.part.chips.blurb": ["Each chip holds billions of tiny cells, one bit in each. The eight chips work together, each handling its share of every transfer.",
      "Svaki čip sadrži milijarde sićušnih ćelija, po jedan bit u svakoj. Osam čipova radi zajedno i svaki obrađuje svoj deo svakog prenosa."],
    "ram.part.chips.fact": ["8 chips × 16 Gbit = 16 GB", "8 čipova × 16 Gbit = 16 GB"],
    "ram.part.pmic": ["Power chip (PMIC)", "Čip za napajanje (PMIC)"],
    "ram.part.pmic.blurb": ["Turns the 5 V from the motherboard into the exact low voltages the chips need. This moved onto the stick with DDR5.",
      "Pretvara 5 V sa matične ploče u tačne niske napone koji trebaju čipovima. Sa DDR5 je prešao na sam modul."],
    "ram.part.pmic.fact": ["The chips run at about 1.1 V", "Čipovi rade na oko 1,1 V"],
    "ram.part.spd": ["Settings chip (SPD)", "Čip sa podešavanjima (SPD)"],
    "ram.part.spd.blurb": ["A tiny memory that tells the motherboard the stick's size, speed and timings when the PC starts.",
      "Mala memorija koja pri pokretanju računara javlja matičnoj ploči kapacitet, brzinu i tajminge modula."],
    "ram.part.spd.fact": ["Stores the XMP / EXPO speed profiles", "Čuva XMP / EXPO profile brzine"],
    "ram.part.pcb": ["Circuit board", "Štampana ploča"],
    "ram.part.pcb.blurb": ["A multi-layer board with carefully length-matched wires, so signals from every chip arrive at the same moment.",
      "Višeslojna ploča sa vezama iste dužine, tako da signali sa svih čipova stižu u istom trenutku."],
    "ram.part.pcb.fact": ["A desktop stick is 133 mm long", "Desktop modul je dugačak 133 mm"],
    "ram.part.contacts": ["Gold contacts", "Pozlaćeni kontakti"],
    "ram.part.contacts.blurb": ["288 contacts along the edge press into the motherboard slot. The notch stops you fitting the wrong type of memory.",
      "288 kontakata duž ivice ulazi u slot na matičnoj ploči. Zarez sprečava da se ubaci pogrešan tip memorije."],
    "ram.part.contacts.fact": ["DDR4 and DDR5 have the notch in different places", "DDR4 i DDR5 imaju zarez na različitim mestima"],

    "ram.grid.eyebrow": ["Chapter 1 · Finding data", "Poglavlje 1 · Pronalaženje podataka"],
    "ram.grid.title": ["Rows and columns", "Redovi i kolone"],
    "ram.grid.p": ["Memory is a huge grid of cells. Each cell is a tiny capacitor: charged means 1, empty means 0. To read a bit, the chip opens a whole row, then picks the column you asked for.",
      "Memorija je ogromna mreža ćelija. Svaka ćelija je sićušni kondenzator: napunjen znači 1, prazan znači 0. Da bi pročitao bit, čip otvara ceo red, pa bira traženu kolonu."],
    "ram.grid.aria": ["Memory cell grid with row and column selection", "Mreža memorijskih ćelija sa izborom reda i kolone"],
    "ram.grid.row": ["Row", "Red"],
    "ram.grid.col": ["Column", "Kolona"],
    "ram.grid.rowdec": ["ROW SELECT", "IZBOR REDA"],
    "ram.grid.coldec": ["COLUMN SELECT", "IZBOR KOLONE"],
    "ram.grid.buffer": ["ROW BUFFER", "BAFER REDA"],
    "ram.grid.out": ["OUT", "IZLAZ"],
    "ram.grid.read": ["Read bit", "Pročitaj bit"],
    "ram.grid.result": ["Row {r}, column {c} → {v}", "Red {r}, kolona {c} → {v}"],
    "ram.grid.s0": ["Pick a row and column, then read.", "Izaberi red i kolonu, pa pročitaj."],
    "ram.grid.s1": ["1. The whole row opens and its charges are copied into the row buffer.", "1. Ceo red se otvara i njegova naelektrisanja kopiraju se u bafer reda."],
    "ram.grid.s2": ["2. The column select picks one bit from the buffer and sends it out.", "2. Izbor kolone uzima jedan bit iz bafera i šalje ga napolje."],
    "ram.grid.s3": ["Reading another bit from the same open row is quicker: step 1 is already done.", "Čitanje još jednog bita iz istog otvorenog reda je brže: prvi korak je već obavljen."],

    "ram.ref.eyebrow": ["Chapter 2 · Refresh", "Poglavlje 2 · Osvežavanje"],
    "ram.ref.title": ["Why RAM forgets", "Zašto RAM zaboravlja"],
    "ram.ref.p": ["The capacitors leak. Within a fraction of a second every 1 would fade into a 0, so the memory reads and rewrites each row about every 32 ms. This is called refresh. Cut the power and nothing refreshes, so the data is gone.",
      "Kondenzatori cure. Za delić sekunde svaka jedinica bi izbledela u nulu, pa memorija otprilike na svakih 32 ms čita i ponovo upisuje svaki red. To se zove osvežavanje. Kad nestane struje, nema osvežavanja i podaci nestaju."],
    "ram.ref.aria": ["Memory cells slowly losing charge and being refreshed row by row", "Memorijske ćelije polako gube naelektrisanje i osvežavaju se red po red"],
    "ram.ref.on": ["Refresh: on", "Osvežavanje: uključeno"],
    "ram.ref.off": ["Refresh: off", "Osvežavanje: isključeno"],
    "ram.ref.powerOn": ["Power: on", "Struja: uključena"],
    "ram.ref.powerOff": ["Power: off", "Struja: isključena"],
    "ram.ref.write": ["Write the data again", "Ponovo upiši podatke"],
    "ram.ref.scale": ["Slowed down: 1 second here ≈ 32 ms in real memory", "Usporeno: 1 sekunda ovde ≈ 32 ms u pravoj memoriji"],
    "ram.ref.kept": ["Data kept: {p}%", "Sačuvano podataka: {p}%"],

    "ram.ddr.eyebrow": ["Chapter 3 · Speed", "Poglavlje 3 · Brzina"],
    "ram.ddr.title": ["Double data rate", "Dvostruka brzina prenosa"],
    "ram.ddr.p": ["DDR memory sends data twice per clock tick: on the rising edge and on the falling edge. A DDR5-6000 stick runs its clock at 3,000 MHz and makes 6,000 million transfers per second, 8 bytes each. Two sticks in two channels double that.",
      "DDR memorija šalje podatke dva puta po otkucaju takta: na uzlaznoj i na silaznoj ivici. Modul DDR5-6000 ima takt od 3.000 MHz i obavlja 6.000 miliona prenosa u sekundi, po 8 bajtova. Dva modula u dva kanala to udvostručuju."],
    "ram.ddr.aria": ["Clock signal with data sent on one edge (SDR) and on both edges (DDR)", "Signal takta sa podacima na jednoj ivici (SDR) i na obe ivice (DDR)"],
    "ram.ddr.sdr": ["SDR · data on rising edge only", "SDR · podaci samo na uzlaznoj ivici"],
    "ram.ddr.ddr": ["DDR · data on both edges", "DDR · podaci na obema ivicama"],
    "ram.ddr.clock": ["CLOCK", "TAKT"],
    "ram.ddr.ch1": ["1 stick", "1 modul"],
    "ram.ddr.ch2": ["2 sticks (dual channel)", "2 modula (dva kanala)"],
    "ram.ddr.read": ["{mt} million transfers/s × 8 bytes × {ch} = {gb} GB/s", "{mt} miliona prenosa/s × 8 bajtova × {ch} = {gb} GB/s"],

    "ram.quiz.q1": ["What happens to the data in RAM when the PC turns off?", "Šta se dešava sa podacima u RAM-u kad se računar ugasi?"],
    "ram.quiz.q1.a0": ["It stays on the chips", "Ostaju na čipovima"],
    "ram.quiz.q1.a1": ["It is lost", "Gube se"],
    "ram.quiz.q1.a2": ["It moves into the CPU cache", "Prelaze u keš procesora"],
    "ram.quiz.q1.why": ["RAM needs power and refresh to hold its charge. That is why files are saved to an SSD.",
      "RAM-u trebaju struja i osvežavanje da zadrži naelektrisanje. Zato se fajlovi čuvaju na SSD-u."],
    "ram.quiz.q2": ["Why does RAM need refreshing?", "Zašto RAM mora da se osvežava?"],
    "ram.quiz.q2.a0": ["Its tiny capacitors slowly leak their charge", "Njegovi sićušni kondenzatori polako gube naelektrisanje"],
    "ram.quiz.q2.a1": ["To make it run faster", "Da bi radio brže"],
    "ram.quiz.q2.a2": ["To delete old programs", "Da bi obrisao stare programe"],
    "ram.quiz.q2.why": ["Unless each row is rewritten about every 32 ms, its 1s fade into 0s.",
      "Ako se svaki red ne upiše ponovo otprilike na svakih 32 ms, jedinice izblede u nule."],
    "ram.quiz.q3": ["What does \"double data rate\" mean?", "Šta znači „dvostruka brzina prenosa“?"],
    "ram.quiz.q3.a0": ["Two sticks work together", "Dva modula rade zajedno"],
    "ram.quiz.q3.a1": ["Data moves on both edges of each clock tick", "Podaci se prenose na obema ivicama svakog otkucaja takta"],
    "ram.quiz.q3.a2": ["Each cell stores two bits", "Svaka ćelija čuva dva bita"],
    "ram.quiz.q3.why": ["The rising and falling edges each carry a transfer, so a 3,000 MHz clock gives 6,000 MT/s.",
      "Uzlazna i silazna ivica nose po jedan prenos, pa takt od 3.000 MHz daje 6.000 MT/s."]
  });

  add({
    "sto.eyebrow": ["Part 04 · Storage", "Deo 04 · Skladište"],
    "sto.full": ["Solid-State Drive", "Poluprovodnički disk"],
    "sto.lede": ["Storage keeps your files, games and operating system while the PC is off. Today that is usually an SSD: flash memory chips with no moving parts, often on a small stick that plugs straight into the motherboard.",
      "Skladište čuva fajlove, igre i operativni sistem i kad je računar ugašen. Danas je to obično SSD: fleš memorijski čipovi bez pokretnih delova, često na maloj pločici koja se utakne direktno u matičnu ploču."],
    "sto.spec.cap": ["Capacity", "Kapacitet"], "sto.spec.cap.v": ["1–4 TB", "1–4 TB"],
    "sto.spec.read": ["Read speed", "Brzina čitanja"], "sto.spec.read.v": ["up to 14,000 MB/s", "do 14.000 MB/s"],
    "sto.spec.access": ["Access time", "Vreme pristupa"], "sto.spec.access.v": ["~0.1 ms", "~0,1 ms"],
    "sto.spec.size": ["Size (M.2 2280)", "Veličina (M.2 2280)"], "sto.spec.size.v": ["22 × 80 mm", "22 × 80 mm"],
    "sto.fineprint": ["A typical 2025 M.2 NVMe SSD. Drag to rotate, slide to take it apart.",
      "Tipičan M.2 NVMe SSD iz 2025. Prevuci da okreneš, a klizačem rastavi."],

    "sto.part.label": ["Label", "Nalepnica"],
    "sto.part.label.blurb": ["The sticker on top is often backed with a thin copper or graphene layer that spreads heat from the chips.",
      "Nalepnica odozgo često ima tanak sloj bakra ili grafena koji širi toplotu sa čipova."],
    "sto.part.label.fact": ["Fast drives can reach 70 °C under load", "Brzi diskovi pod opterećenjem dostižu 70 °C"],
    "sto.part.nand": ["Flash memory (NAND)", "Fleš memorija (NAND)"],
    "sto.part.nand.blurb": ["Where your files actually live. Each package holds stacked silicon dies with billions of cells that keep their charge without power.",
      "Ovde se zaista nalaze tvoji fajlovi. Svako kućište sadrži naslagane silicijumske pločice sa milijardama ćelija koje zadržavaju naelektrisanje bez struje."],
    "sto.part.nand.fact": ["Current flash stacks over 200 layers of cells", "Današnji fleš ima više od 200 slojeva ćelija"],
    "sto.part.controller": ["Controller", "Kontroler"],
    "sto.part.controller.blurb": ["The SSD's own small processor. It spreads writes evenly so no cell wears out early, fixes errors, and talks to the PC over PCIe.",
      "Sopstveni mali procesor SSD-a. Ravnomerno raspoređuje upis da se nijedna ćelija ne istroši pre vremena, ispravlja greške i komunicira sa računarom preko PCIe veze."],
    "sto.part.controller.fact": ["Uses 4 PCIe lanes (NVMe)", "Koristi 4 PCIe linije (NVMe)"],
    "sto.part.dram": ["DRAM cache", "DRAM keš"],
    "sto.part.dram.blurb": ["A small RAM chip holding the map of where every piece of data sits in the flash, so lookups are fast.",
      "Mali RAM čip koji čuva mapu gde se u fleš memoriji nalazi svaki podatak, pa je pronalaženje brzo."],
    "sto.part.dram.fact": ["About 1 GB of DRAM per 1 TB of flash", "Oko 1 GB DRAM-a na 1 TB fleša"],
    "sto.part.pcb": ["Circuit board", "Štampana ploča"],
    "sto.part.pcb.blurb": ["A small board in the M.2 2280 size: 22 mm wide and 80 mm long. One screw holds it to the motherboard.",
      "Mala ploča formata M.2 2280: široka 22 mm i dugačka 80 mm. Za matičnu ploču je drži jedan šraf."],
    "sto.part.pcb.fact": ["No cables: power and data come through the slot", "Bez kablova: struja i podaci stižu kroz slot"],
    "sto.part.connector": ["M.2 connector", "M.2 konektor"],
    "sto.part.connector.blurb": ["Gold contacts that slide into the M.2 slot. The gap between them (the M key) shows the drive uses PCIe NVMe.",
      "Pozlaćeni kontakti koji ulaze u M.2 slot. Zarez među njima (M ključ) pokazuje da disk koristi PCIe NVMe."],
    "sto.part.connector.fact": ["PCIe 4.0 ×4: up to ~8 GB/s", "PCIe 4.0 ×4: do ~8 GB/s"],

    "sto.hdd.eyebrow": ["Chapter 1 · Two kinds of drive", "Poglavlje 1 · Dve vrste diskova"],
    "sto.hdd.title": ["HDD vs SSD", "HDD protiv SSD-a"],
    "sto.hdd.p": ["A hard disk drive (HDD) stores data as magnetic spots on spinning platters. An arm has to move to the right track and wait for the data to spin past. An SSD has no moving parts, so it reaches any data almost instantly.",
      "Hard disk (HDD) čuva podatke kao magnetne tačke na pločama koje se okreću. Ručica mora da se pomeri do prave staze i sačeka da podatak prođe ispod nje. SSD nema pokretnih delova, pa do bilo kog podatka stiže skoro trenutno."],
    "sto.hdd.aria": ["A hard disk and an SSD reading the same scattered files", "Hard disk i SSD čitaju iste razbacane fajlove"],
    "sto.hdd.hdd": ["HDD · 7,200 rpm", "HDD · 7.200 obrtaja/min"],
    "sto.hdd.ssd": ["SSD · NVMe", "SSD · NVMe"],
    "sto.hdd.platter": ["PLATTER", "PLOČA"],
    "sto.hdd.arm": ["ARM", "RUČICA"],
    "sto.hdd.chips": ["FLASH CHIPS", "FLEŠ ČIPOVI"],
    "sto.hdd.run": ["Read 8 scattered files", "Pročitaj 8 razbacanih fajlova"],
    "sto.hdd.count": ["{n} of 8 files", "{n} od 8 fajlova"],
    "sto.hdd.done": ["8 files · ≈ {ms} ms in real life", "8 fajlova · ≈ {ms} ms u stvarnosti"],
    "sto.hdd.note": ["Heavily slowed down. Each HDD read waits ~8 ms for the arm and ~4 ms for the platter; an SSD read takes ~0.1 ms.",
      "Jako usporeno. Svako HDD čitanje čeka ~8 ms na ručicu i ~4 ms na ploču; SSD čitanje traje ~0,1 ms."],

    "sto.cell.eyebrow": ["Chapter 2 · Flash memory", "Poglavlje 2 · Fleš memorija"],
    "sto.cell.title": ["How flash keeps a bit", "Kako fleš pamti bit"],
    "sto.cell.p1": ["Each flash cell is a transistor with an extra, fully insulated floating gate. Pushing electrons onto it changes how the transistor switches. The insulation traps them, so they stay put with the power off, for years.",
      "Svaka fleš ćelija je tranzistor sa dodatnim, potpuno izolovanim plutajućim gejtom. Kad se na njega uguraju elektroni, menja se način na koji tranzistor provodi. Izolacija ih zadržava, pa ostaju tu i bez struje, godinama."],
    "sto.cell.p2": ["To fit more data, a cell can hold several amounts of charge and so store several bits. More levels means more data, but they are harder to tell apart, so the cell is slower and wears out sooner.",
      "Da bi stalo više podataka, ćelija može da drži nekoliko različitih količina naelektrisanja i tako čuva više bitova. Više nivoa znači više podataka, ali ih je teže razlikovati, pa je ćelija sporija i brže se troši."],
    "sto.cell.aria": ["Flash cell with electrons on its floating gate and its charge levels", "Fleš ćelija sa elektronima na plutajućem gejtu i njeni nivoi naelektrisanja"],
    "sto.cell.cg": ["CONTROL GATE", "KONTROLNI GEJT"],
    "sto.cell.fg": ["FLOATING GATE", "PLUTAJUĆI GEJT"],
    "sto.cell.ins": ["INSULATOR", "IZOLATOR"],
    "sto.cell.ch": ["CHANNEL", "KANAL"],
    "sto.cell.levels": ["CHARGE LEVELS", "NIVOI NAELEKTRISANJA"],
    "sto.cell.store": ["Store a random value", "Upiši nasumičnu vrednost"],
    "sto.cell.read": ["{name} · bits per cell: {b} · levels: {l} · lasts ~{c} writes", "{name} · bitova po ćeliji: {b} · nivoa: {l} · izdrži ~{c} upisa"],
    "sto.cell.value": ["Stored: {v}", "Upisano: {v}"],

    "sto.speed.eyebrow": ["Chapter 3 · Speed", "Poglavlje 3 · Brzina"],
    "sto.speed.title": ["How fast is fast?", "Koliko je brzo brzo?"],
    "sto.speed.p": ["Sequential read speed decides how quickly big files load. This is how long a 10 GB game would take to load from each type of drive at its top speed.",
      "Brzina sekvencijalnog čitanja određuje koliko brzo se učitavaju veliki fajlovi. Ovoliko bi trajalo učitavanje igre od 10 GB sa svake vrste diska pri najvećoj brzini."],
    "sto.speed.hdd": ["Hard disk", "Hard disk"], "sto.speed.hdd.sub": ["SATA · spinning", "SATA · sa pločama"],
    "sto.speed.sata": ["SATA SSD", "SATA SSD"], "sto.speed.sata.sub": ["2.5-inch, cable", "2,5 inča, sa kablom"],
    "sto.speed.g3": ["NVMe SSD", "NVMe SSD"], "sto.speed.g3.sub": ["M.2 · PCIe 3.0", "M.2 · PCIe 3.0"],
    "sto.speed.g4": ["NVMe SSD", "NVMe SSD"], "sto.speed.g4.sub": ["M.2 · PCIe 4.0", "M.2 · PCIe 4.0"],
    "sto.speed.g5": ["NVMe SSD", "NVMe SSD"], "sto.speed.g5.sub": ["M.2 · PCIe 5.0", "M.2 · PCIe 5.0"],
    "sto.speed.row": ["{s} MB/s · {t} s", "{s} MB/s · {t} s"],
    "sto.speed.run": ["Load the game", "Učitaj igru"],
    "sto.speed.note": ["Real loading also waits for the CPU to unpack files, so the gap is smaller in practice.",
      "Pravo učitavanje čeka i procesor da raspakuje fajlove, pa je razlika u praksi manja."],

    "sto.quiz.q1": ["Why is an SSD so much faster than an HDD at finding files?", "Zašto SSD mnogo brže od HDD-a pronalazi fajlove?"],
    "sto.quiz.q1.a0": ["It has no moving parts to wait for", "Nema pokretnih delova na koje se čeka"],
    "sto.quiz.q1.a1": ["Its platters spin faster", "Njegove ploče se brže okreću"],
    "sto.quiz.q1.a2": ["It uses stronger magnets", "Koristi jače magnete"],
    "sto.quiz.q1.why": ["An HDD must move its arm and wait for the platter to turn; an SSD reads any cell electronically.",
      "HDD mora da pomeri ručicu i sačeka da se ploča okrene; SSD elektronski čita bilo koju ćeliju."],
    "sto.quiz.q2": ["Why does an SSD keep your files with the power off?", "Zašto SSD čuva fajlove i kad nema struje?"],
    "sto.quiz.q2.a0": ["A small battery keeps it running", "Mala baterija ga drži uključenim"],
    "sto.quiz.q2.a1": ["Electrons are trapped on an insulated floating gate", "Elektroni su zarobljeni na izolovanom plutajućem gejtu"],
    "sto.quiz.q2.a2": ["The files are copied into RAM", "Fajlovi se kopiraju u RAM"],
    "sto.quiz.q2.why": ["The insulation holds the electrons in place without any power, unlike the leaky capacitors in RAM.",
      "Izolacija drži elektrone na mestu bez struje, za razliku od kondenzatora u RAM-u koji cure."],
    "sto.quiz.q3": ["Which type of flash stores the most bits in each cell?", "Koja vrsta fleša čuva najviše bitova u svakoj ćeliji?"],
    "sto.quiz.q3.a0": ["SLC", "SLC"],
    "sto.quiz.q3.a1": ["TLC", "TLC"],
    "sto.quiz.q3.a2": ["QLC", "QLC"],
    "sto.quiz.q3.why": ["QLC stores 4 bits using 16 charge levels, but it is slower and wears out sooner.",
      "QLC čuva 4 bita pomoću 16 nivoa naelektrisanja, ali je sporiji i brže se troši."]
  });

  add({
    "mb.eyebrow": ["Part 05 · The motherboard", "Deo 05 · Matična ploča"],
    "mb.title": ["Motherboard", "Matična ploča"],
    "mb.full": ["Where every part connects", "Mesto gde se sve povezuje"],
    "mb.lede": ["The motherboard connects every part of the PC. It carries power to each one, links them with fast data paths, and holds the firmware (BIOS) that starts the computer.",
      "Matična ploča povezuje sve delove računara. Do svakog dovodi struju, povezuje ih brzim putevima za podatke i čuva firmver (BIOS) koji pokreće računar."],
    "mb.spec.size": ["ATX size", "ATX format"], "mb.spec.size.v": ["305 × 244 mm", "305 × 244 mm"],
    "mb.spec.layers": ["Copper layers", "Bakarni slojevi"], "mb.spec.layers.v": ["6–10", "6–10"],
    "mb.spec.slots": ["RAM slots", "Slotovi za RAM"], "mb.spec.slots.v": ["2–4", "2–4"],
    "mb.spec.phases": ["Power phases", "Faze napajanja"], "mb.spec.phases.v": ["8–24", "8–24"],
    "mb.fineprint": ["A typical 2025 ATX desktop board. Drag to rotate, slide to lift the parts off.",
      "Tipična ATX desktop ploča iz 2025. Prevuci da okreneš, a klizačem podigni delove."],

    "mb.part.socket": ["CPU socket", "Podnožje procesora"],
    "mb.part.socket.blurb": ["Where the processor sits. A metal frame and lever press the CPU down onto about 1,700 tiny spring pins.",
      "Mesto gde stoji procesor. Metalni okvir i poluga pritiskaju ga na oko 1.700 sićušnih opružnih iglica."],
    "mb.part.socket.fact": ["Bent pins are the classic building mistake", "Savijene iglice su klasična greška pri sklapanju"],
    "mb.part.vrm": ["VRM heatsinks", "Hladnjaci VRM-a"],
    "mb.part.vrm.blurb": ["They cover the voltage regulators that turn 12 V into the ~1.2 V the CPU needs. These get hot under heavy load.",
      "Pokrivaju regulatore napona koji pretvaraju 12 V u ~1,2 V potrebnih procesoru. Pod velikim opterećenjem se zagreju."],
    "mb.part.vrm.fact": ["Can feed the CPU over 200 amps", "Mogu da daju procesoru preko 200 A"],
    "mb.part.dimm": ["RAM slots", "Slotovi za RAM"],
    "mb.part.dimm.blurb": ["Four slots wired straight to the CPU's memory controller. With two sticks, use every other slot to get dual channel.",
      "Četiri slota povezana direktno na memorijski kontroler procesora. Sa dva modula koristi svaki drugi slot da dobiješ dva kanala."],
    "mb.part.dimm.fact": ["The latches click shut when a stick is fully in", "Kopče škljocnu kad modul potpuno legne"],
    "mb.part.pcie": ["PCIe slots", "PCIe slotovi"],
    "mb.part.pcie.blurb": ["Long slots for the graphics card and other expansion cards. The top one is reinforced with metal, because big graphics cards are heavy.",
      "Dugački slotovi za grafičku karticu i druge kartice. Gornji je ojačan metalom, jer su velike grafičke kartice teške."],
    "mb.part.pcie.fact": ["Top slot: PCIe 5.0 ×16 to the CPU", "Gornji slot: PCIe 5.0 ×16 do procesora"],
    "mb.part.m2": ["M.2 slot and cover", "M.2 slot i poklopac"],
    "mb.part.m2.blurb": ["Holds an NVMe SSD flat against the board. The metal cover with a thermal pad keeps the drive cool.",
      "Drži NVMe SSD položen na ploči. Metalni poklopac sa termalnom podlogom hladi disk."],
    "mb.part.m2.fact": ["Main M.2 slot: 4 lanes straight to the CPU", "Glavni M.2 slot: 4 linije direktno do procesora"],
    "mb.part.chipset": ["Chipset", "Čipset"],
    "mb.part.chipset.blurb": ["A helper chip that adds more USB and SATA ports, networking and extra M.2 slots. They all share one link to the CPU.",
      "Pomoćni čip koji dodaje USB i SATA portove, mrežu i dodatne M.2 slotove. Svi dele jednu vezu do procesora."],
    "mb.part.chipset.fact": ["Its link to the CPU carries ~8–16 GB/s", "Njegova veza do procesora prenosi ~8–16 GB/s"],
    "mb.part.io": ["Rear I/O", "Zadnji priključci"],
    "mb.part.io.blurb": ["The ports on the back of the PC: USB, network, audio, and display outputs for the CPU's integrated graphics.",
      "Priključci na zadnjoj strani računara: USB, mreža, zvuk i video izlazi za integrisanu grafiku procesora."],
    "mb.part.io.fact": ["USB4 carries up to 40 Gbit/s", "USB4 prenosi do 40 Gbit/s"],
    "mb.part.board": ["Circuit board", "Štampana ploča"],
    "mb.part.board.blurb": ["Six to ten layers of copper wiring, plus the power connectors, fan headers and the BIOS chip that starts the PC.",
      "Šest do deset slojeva bakarnih veza, uz konektore za napajanje, priključke za ventilatore i BIOS čip koji pokreće računar."],
    "mb.part.board.fact": ["A coin battery keeps the BIOS clock running", "Baterija u obliku novčića održava sat BIOS-a"],

    "mb.map.eyebrow": ["Chapter 1 · Connections", "Poglavlje 1 · Veze"],
    "mb.map.title": ["The roads between parts", "Putevi između delova"],
    "mb.map.p": ["The motherboard is a map of roads. The fastest parts connect straight to the CPU: RAM, the graphics card and the main SSD. Slower things like USB, network and extra drives go through the chipset, which shares one link to the CPU. Pick a part to follow its data.",
      "Matična ploča je mapa puteva. Najbrži delovi povezani su direktno sa procesorom: RAM, grafička kartica i glavni SSD. Sporiji uređaji, poput USB-a, mreže i dodatnih diskova, idu preko čipseta, koji deli jednu vezu do procesora. Izaberi deo i prati njegove podatke."],
    "mb.map.aria": ["Diagram of how parts connect to the CPU and chipset", "Dijagram povezivanja delova sa procesorom i čipsetom"],
    "mb.map.route": ["Route", "Put"],
    "mb.dev.cpu": ["CPU", "Procesor"],
    "mb.dev.ram": ["RAM", "RAM"],
    "mb.dev.gpu": ["Graphics card", "Grafička kartica"],
    "mb.dev.ssd": ["M.2 SSD", "M.2 SSD"],
    "mb.dev.chipset": ["Chipset", "Čipset"],
    "mb.dev.usb": ["USB ports", "USB portovi"],
    "mb.dev.net": ["Network", "Mreža"],
    "mb.dev.sata": ["SATA drives", "SATA diskovi"],
    "mb.dev.audio": ["Audio", "Zvuk"],
    "mb.dev.ram.t": ["Straight to the CPU's memory controller: the shortest, fastest road on the board.", "Direktno do memorijskog kontrolera procesora: najkraći i najbrži put na ploči."],
    "mb.dev.gpu.t": ["16 PCIe lanes straight to the CPU, so textures and frames move without waiting.", "16 PCIe linija direktno do procesora, pa se teksture i frejmovi prenose bez čekanja."],
    "mb.dev.ssd.t": ["The main M.2 slot has its own 4 lanes to the CPU, so games load fast.", "Glavni M.2 slot ima sopstvene 4 linije do procesora, pa se igre brzo učitavaju."],
    "mb.dev.chipset.t": ["A hub for slower devices. They all share its one link to the CPU.", "Čvorište za sporije uređaje. Svi dele njegovu jednu vezu do procesora."],
    "mb.dev.usb.t": ["USB → chipset → CPU. Plenty for a mouse, keyboard or USB stick.", "USB → čipset → procesor. Sasvim dovoljno za miš, tastaturu ili fleš."],
    "mb.dev.net.t": ["Network → chipset → CPU. Even 2.5 Gbit/s internet uses a small part of the link.", "Mreža → čipset → procesor. Čak i internet od 2,5 Gbit/s koristi mali deo veze."],
    "mb.dev.sata.t": ["SATA → chipset → CPU. Older 2.5-inch SSDs and hard disks, up to ~0.6 GB/s each.", "SATA → čipset → procesor. Stariji SSD-ovi od 2,5 inča i hard diskovi, do ~0,6 GB/s svaki."],
    "mb.dev.audio.t": ["Audio → chipset → CPU. Sound needs very little bandwidth.", "Zvuk → čipset → procesor. Zvuku treba vrlo malo propusnog opsega."],

    "mb.pcie.eyebrow": ["Chapter 2 · Expansion slots", "Poglavlje 2 · Slotovi za proširenje"],
    "mb.pcie.title": ["PCIe lanes", "PCIe linije"],
    "mb.pcie.p": ["PCI Express connects cards and SSDs using lanes: pairs of wires that carry data in both directions. More lanes move more data at once, and each new generation doubles the speed of every lane.",
      "PCI Express povezuje kartice i SSD-ove pomoću linija: parova žica koje prenose podatke u oba smera. Više linija prenosi više podataka odjednom, a svaka nova generacija udvostručuje brzinu svake linije."],
    "mb.pcie.aria": ["Data moving over PCIe lanes", "Podaci se kreću PCIe linijama"],
    "mb.pcie.lanes": ["Lanes", "Linije"],
    "mb.pcie.gen": ["Generation", "Generacija"],
    "mb.pcie.device": ["DEVICE", "UREĐAJ"],
    "mb.pcie.read": ["PCIe {g} ×{n}: {n} × ~{per} GB/s = ~{tot} GB/s each way", "PCIe {g} ×{n}: {n} × ~{per} GB/s = ~{tot} GB/s u svakom smeru"],

    "mb.vrm.eyebrow": ["Chapter 3 · Power delivery", "Poglavlje 3 · Napajanje"],
    "mb.vrm.title": ["Feeding the CPU", "Kako se hrani procesor"],
    "mb.vrm.p": ["The power supply sends 12 V, but the CPU wants about 1.2 V at up to 200 amps. The VRM around the socket converts it with several phases that take turns, so each phase carries only part of the current and stays cool.",
      "Napajanje šalje 12 V, a procesoru treba oko 1,2 V i do 200 ampera. VRM oko podnožja to pretvara pomoću više faza koje se smenjuju, pa svaka faza nosi samo deo struje i ostaje hladna."],
    "mb.vrm.aria": ["Power phases taking turns to feed the CPU", "Faze napajanja se smenjuju dok napajaju procesor"],
    "mb.vrm.phases": ["Phases", "Faze"],
    "mb.vrm.load": ["CPU load", "Opterećenje"],
    "mb.vrm.idle": ["Idle", "Mirovanje"],
    "mb.vrm.game": ["Gaming", "Igranje"],
    "mb.vrm.heavy": ["Heavy work", "Težak posao"],
    "mb.vrm.in": ["12 V FROM THE PSU", "12 V IZ NAPAJANJA"],
    "mb.vrm.out": ["~1.2 V TO THE CPU", "~1,2 V DO PROCESORA"],
    "mb.vrm.read": ["{a} A ÷ {p} = {each} A per phase", "{a} A ÷ {p} = {each} A po fazi"],
    "mb.vrm.cool": ["cool", "hladno"], "mb.vrm.warm": ["warm", "toplo"], "mb.vrm.hot": ["hot", "vruće"],

    "mb.quiz.q1": ["Which of these connects straight to the CPU?", "Šta je od ovoga direktno povezano sa procesorom?"],
    "mb.quiz.q1.a0": ["The USB ports", "USB portovi"],
    "mb.quiz.q1.a1": ["The graphics card", "Grafička kartica"],
    "mb.quiz.q1.a2": ["The audio chip", "Zvučni čip"],
    "mb.quiz.q1.why": ["The GPU, RAM and main SSD get their own fast lanes to the CPU; slower devices share the chipset's link.",
      "GPU, RAM i glavni SSD imaju sopstvene brze linije do procesora; sporiji uređaji dele vezu čipseta."],
    "mb.quiz.q2": ["What does ×16 mean in \"PCIe ×16\"?", "Šta znači ×16 u „PCIe ×16“?"],
    "mb.quiz.q2.a0": ["16 lanes of data", "16 linija za podatke"],
    "mb.quiz.q2.a1": ["The 16th generation", "Šesnaesta generacija"],
    "mb.quiz.q2.a2": ["Exactly 16 GB/s", "Tačno 16 GB/s"],
    "mb.quiz.q2.why": ["×16 is the number of lanes. How fast each lane is depends on the generation.", "×16 je broj linija. Brzina svake linije zavisi od generacije."],
    "mb.quiz.q3": ["Why does the VRM use many phases?", "Zašto VRM koristi mnogo faza?"],
    "mb.quiz.q3.a0": ["To share the current so each phase stays cool", "Da podele struju, pa svaka faza ostaje hladna"],
    "mb.quiz.q3.a1": ["To raise the voltage to 12 V", "Da podignu napon na 12 V"],
    "mb.quiz.q3.a2": ["To charge the BIOS battery", "Da pune bateriju BIOS-a"],
    "mb.quiz.q3.why": ["200 A through one phase would overheat it. Eight phases carry about 25 A each.", "200 A kroz jednu fazu bi je pregrejalo. Osam faza nosi po oko 25 A."]
  });

  add({
    "psu.eyebrow": ["Part 06 · The power supply", "Deo 06 · Napajanje"],
    "psu.full": ["Power supply unit", "Jedinica za napajanje"],
    "psu.lede": ["The power supply turns alternating current from the wall into steady direct current: mostly 12 V for the CPU and graphics card, plus 5 V and 3.3 V for smaller parts. It also shuts everything off safely if something goes wrong.",
      "Napajanje pretvara naizmeničnu struju iz zida u stabilnu jednosmernu: najviše 12 V za procesor i grafičku karticu, plus 5 V i 3,3 V za manje delove. Ako nešto pođe naopako, bezbedno sve isključi."],
    "psu.spec.power": ["Power", "Snaga"], "psu.spec.power.v": ["550–1200 W", "550–1200 W"],
    "psu.spec.rail": ["Main output", "Glavni izlaz"], "psu.spec.rail.v": ["12 V DC", "12 V DC"],
    "psu.spec.eff": ["Efficiency", "Efikasnost"], "psu.spec.eff.v": ["85–94%", "85–94%"],
    "psu.spec.fan": ["Fan", "Ventilator"], "psu.spec.fan.v": ["120–140 mm", "120–140 mm"],
    "psu.fineprint": ["A typical 850 W ATX unit. Drag to rotate, slide to take it apart.",
      "Tipično ATX napajanje od 850 W. Prevuci da okreneš, a klizačem rastavi."],

    "psu.part.fan": ["Fan", "Ventilator"],
    "psu.part.fan.blurb": ["A 135 mm fan pulls air through the unit. Many PSUs stop the fan completely at low load, so they are silent.",
      "Ventilator od 135 mm provlači vazduh kroz jedinicu. Mnoga napajanja potpuno zaustave ventilator pri malom opterećenju, pa su nečujna."],
    "psu.part.fan.fact": ["In most cases it faces down and pulls air from under the PC", "U većini kućišta okrenut je nadole i uzima vazduh ispod računara"],
    "psu.part.case": ["Steel case", "Metalno kućište"],
    "psu.part.case.blurb": ["Holds everything and blocks electrical noise. The back has the wall socket and the on/off switch.",
      "Drži sve delove i blokira električne smetnje. Na zadnjoj strani su utičnica za kabl i prekidač."],
    "psu.part.case.fact": ["Never open a PSU: its capacitors can stay charged after unplugging", "Nikad ne otvaraj napajanje: kondenzatori ostaju napunjeni i posle isključivanja"],
    "psu.part.transformer": ["Transformer", "Transformator"],
    "psu.part.transformer.blurb": ["Steps the high voltage down to a low one and keeps the PC side safely separated from the wall.",
      "Spušta visok napon na nizak i bezbedno odvaja stranu računara od zida."],
    "psu.part.transformer.fact": ["Switching ~100,000 times a second lets it fit in your palm", "Pošto radi ~100.000 puta u sekundi, staje na dlan"],
    "psu.part.caps": ["Capacitors", "Kondenzatori"],
    "psu.part.caps.blurb": ["The big capacitor stores energy to smooth the power and carry the PC through tiny dips. Smaller ones clean up the outputs.",
      "Veliki kondenzator čuva energiju da izravna napon i premosti kratke padove. Manji čiste izlazne napone."],
    "psu.part.caps.fact": ["The big one charges to about 400 V", "Veliki se puni do oko 400 V"],
    "psu.part.heatsinks": ["Heatsinks", "Hladnjaci"],
    "psu.part.heatsinks.blurb": ["The fast switching transistors and diodes are bolted to these aluminium fins, because they turn part of the power into heat.",
      "Brzi prekidački tranzistori i diode pričvršćeni su za ova aluminijumska rebra, jer deo snage pretvaraju u toplotu."],
    "psu.part.heatsinks.fact": ["At 90% efficiency, an 800 W load still makes ~90 W of heat", "Sa 90% efikasnosti, potrošnja od 800 W i dalje pravi ~90 W toplote"],
    "psu.part.modular": ["Modular connectors", "Modularni priključci"],
    "psu.part.modular.blurb": ["Cables plug in here, so you attach only the ones you need and keep the inside of the PC tidy.",
      "Ovde se uključuju kablovi, pa povežeš samo one koji ti trebaju i unutrašnjost ostaje uredna."],
    "psu.part.modular.fact": ["Use only the cables that came with this PSU: pin layouts differ", "Koristi samo kablove koji su došli uz ovo napajanje: raspored pinova se razlikuje"],
    "psu.part.pcb": ["Circuit board", "Štampana ploča"],
    "psu.part.pcb.blurb": ["Filters the incoming power and controls the whole conversion. Thick copper tracks carry the large currents.",
      "Filtrira ulaznu struju i upravlja celim pretvaranjem. Debeli bakarni vodovi nose velike struje."],
    "psu.part.pcb.fact": ["Protection circuits cut the power on a short circuit or overload", "Zaštitna kola prekidaju struju pri kratkom spoju ili preopterećenju"],

    "psu.path.eyebrow": ["Chapter 1 · Conversion", "Poglavlje 1 · Pretvaranje"],
    "psu.path.title": ["From the wall to 12 V", "Od utičnice do 12 V"],
    "psu.path.p": ["Power from the wall is high-voltage alternating current. Step through the stages to see how the PSU turns it into the low, steady voltage a PC needs.",
      "Struja iz zida je naizmenična i visokog napona. Prođi kroz korake i vidi kako je napajanje pretvara u nizak, stabilan napon koji računaru treba."],
    "psu.path.aria": ["Voltage at each stage inside the power supply", "Napon u svakom koraku unutar napajanja"],
    "psu.path.volt": ["VOLTAGE", "NAPON"],
    "psu.path.time": ["TIME", "VREME"],
    "psu.path.s0": ["{n} Wall", "{n} Utičnica"],
    "psu.path.s1": ["{n} Rectify", "{n} Ispravljanje"],
    "psu.path.s2": ["{n} Smooth", "{n} Izravnavanje"],
    "psu.path.s3": ["{n} Chop", "{n} Seckanje"],
    "psu.path.s4": ["{n} Transform", "{n} Transformacija"],
    "psu.path.s5": ["{n} Clean 12 V", "{n} Čistih 12 V"],
    "psu.path.t0": ["In Europe the socket gives alternating current: the voltage swings between +325 V and −325 V, 50 times a second.",
      "U Evropi utičnica daje naizmeničnu struju: napon se ljulja između +325 V i −325 V, 50 puta u sekundi."],
    "psu.path.t1": ["A bridge of four diodes flips the negative half up, so the current flows only one way.",
      "Most od četiri diode okreće negativnu polovinu nagore, pa struja teče samo u jednom smeru."],
    "psu.path.t2": ["A boost circuit and the big capacitor fill the dips between the bumps. What is left is a high, nearly flat DC voltage of about 400 V.",
      "Pojačavač i veliki kondenzator popunjavaju udubljenja između talasa. Ostaje visok, skoro ravan jednosmerni napon od oko 400 V."],
    "psu.path.t3": ["Fast transistors switch that voltage on and off about 100,000 times a second, making sharp pulses.",
      "Brzi tranzistori uključuju i isključuju taj napon oko 100.000 puta u sekundi i prave oštre impulse."],
    "psu.path.t4": ["The transformer turns the 400 V pulses into low-voltage pulses. It also keeps the PC electrically separated from the wall.",
      "Transformator pretvara impulse od 400 V u impulse niskog napona. Takođe električno odvaja računar od zida."],
    "psu.path.t5": ["Diodes, coils and capacitors turn the pulses into a steady 12 V. Small converters then make 5 V and 3.3 V from it.",
      "Diode, kalemovi i kondenzatori pretvaraju impulse u stabilnih 12 V. Mali pretvarači od toga zatim prave 5 V i 3,3 V."],

    "psu.budget.eyebrow": ["Chapter 2 · Power budget", "Poglavlje 2 · Budžet snage"],
    "psu.budget.title": ["How many watts?", "Koliko vati?"],
    "psu.budget.p": ["Add up what your parts draw, then leave about a quarter extra. Graphics cards can jump above their rating for a split second, and a PSU runs cooler and quieter when it is not at its limit.",
      "Saberi koliko troše delovi, pa ostavi oko četvrtinu viška. Grafičke kartice na tren mogu da pređu svoju deklarisanu potrošnju, a napajanje je hladnije i tiše kad ne radi na granici."],
    "psu.budget.aria": ["Bar showing the power each part draws and the PSU size to choose", "Traka sa snagom koju troši svaki deo i veličinom napajanja koju treba izabrati"],
    "psu.budget.cpu": ["CPU", "Procesor"],
    "psu.budget.gpu": ["Graphics", "Grafika"],
    "psu.budget.rest": ["Rest", "Ostalo"],
    "psu.budget.extra": ["+25%", "+25%"],
    "psu.budget.psu": ["{w} W PSU", "Napajanje {w} W"],
    "psu.budget.cpu0": ["Efficient", "Štedljiv"],
    "psu.budget.cpu1": ["Gaming", "Za igre"],
    "psu.budget.cpu2": ["High-end", "Najjači"],
    "psu.budget.gpu0": ["Built-in", "Integrisana"],
    "psu.budget.gpu1": ["Mid-range", "Srednja"],
    "psu.budget.gpu2": ["High-end", "Jaka"],
    "psu.budget.gpu3": ["Top", "Najjača"],
    "psu.budget.restNote": ["Rest = board, RAM, drives and fans, about 50 W", "Ostalo = ploča, RAM, diskovi i ventilatori, oko 50 W"],
    "psu.budget.read": ["{w} W × 1.25 = {h} W → choose a {psu} W PSU", "{w} W × 1,25 = {h} W → izaberi napajanje od {psu} W"],
    "psu.budget.cables": ["Cables this PC needs", "Kablovi koji ovom računaru trebaju"],
    "psu.conn.atx": ["24-pin ATX", "24-pinski ATX"], "psu.conn.atx.t": ["Motherboard", "Matična ploča"],
    "psu.conn.eps": ["8-pin EPS", "8-pinski EPS"], "psu.conn.eps.t": ["CPU power", "Napajanje procesora"],
    "psu.conn.pcie": ["8-pin PCIe", "8-pinski PCIe"], "psu.conn.pcie.t": ["Graphics card, 150 W each", "Grafička kartica, po 150 W"],
    "psu.conn.hpwr": ["12V-2×6", "12V-2×6"], "psu.conn.hpwr.t": ["Graphics card, up to 600 W", "Grafička kartica, do 600 W"],
    "psu.conn.sata": ["SATA power", "SATA napajanje"], "psu.conn.sata.t": ["Disks, fans and lights", "Diskovi, ventilatori i svetla"],
    "psu.conn.none": ["Not needed", "Nije potreban"],

    "psu.eff.eyebrow": ["Chapter 3 · Efficiency", "Poglavlje 3 · Efikasnost"],
    "psu.eff.title": ["Where the lost watts go", "Gde nestaju vati"],
    "psu.eff.p": ["No PSU is perfect: some power always turns into heat. The 80 Plus badge tells you how efficient a unit is. A better one takes less from the wall for the same PC and stays cooler.",
      "Nijedno napajanje nije savršeno: deo snage se uvek pretvara u toplotu. Oznaka 80 Plus govori koliko je jedinica efikasna. Bolja uzima manje iz zida za isti računar i ostaje hladnija."],
    "psu.eff.aria": ["Power from the wall splitting into power for the PC and heat", "Snaga iz zida se deli na snagu za računar i toplotu"],
    "psu.eff.badge": ["Badge", "Oznaka"],
    "psu.eff.load": ["PC uses", "Računar troši"],
    "psu.eff.wall": ["FROM THE WALL", "IZ ZIDA"],
    "psu.eff.pc": ["TO THE PC", "DO RAČUNARA"],
    "psu.eff.heat": ["LOST AS HEAT", "GUBI SE KAO TOPLOTA"],
    "psu.eff.read": ["{out} W ÷ {eff} = {wall} W from the wall, {heat} W of heat", "{out} W ÷ {eff} = {wall} W iz zida, {heat} W toplote"],
    "psu.eff.note": ["Efficiency at half load. On 230 V, as in Europe, each badge is about 2% better.",
      "Efikasnost na pola opterećenja. Na 230 V, kao u Evropi, svaka oznaka je oko 2% bolja."],

    "psu.quiz.q1": ["What does the PSU mainly give the CPU and graphics card?", "Šta napajanje uglavnom daje procesoru i grafičkoj kartici?"],
    "psu.quiz.q1.a0": ["230 V AC", "230 V naizmenične struje"],
    "psu.quiz.q1.a1": ["12 V DC", "12 V jednosmerne struje"],
    "psu.quiz.q1.a2": ["1.2 V DC", "1,2 V jednosmerne struje"],
    "psu.quiz.q1.why": ["The PSU makes 12 V. The VRMs on the motherboard and graphics card turn it into the ~1 V the chips use.",
      "Napajanje pravi 12 V. VRM na matičnoj ploči i grafičkoj kartici to pretvara u ~1 V koji čipovi koriste."],
    "psu.quiz.q2": ["A 90% efficient PSU gives the PC 450 W. How much does it take from the wall?", "Napajanje sa 90% efikasnosti daje računaru 450 W. Koliko uzima iz zida?"],
    "psu.quiz.q2.a0": ["405 W", "405 W"],
    "psu.quiz.q2.a1": ["450 W", "450 W"],
    "psu.quiz.q2.a2": ["500 W", "500 W"],
    "psu.quiz.q2.why": ["450 ÷ 0.9 = 500 W. The other 50 W becomes heat.", "450 ÷ 0,9 = 500 W. Ostalih 50 W postaje toplota."],
    "psu.quiz.q3": ["Why should you never open a PSU?", "Zašto nikad ne treba otvarati napajanje?"],
    "psu.quiz.q3.a0": ["The big capacitor can stay charged to hundreds of volts", "Veliki kondenzator može ostati napunjen na stotine volti"],
    "psu.quiz.q3.a1": ["The fan would stop working", "Ventilator bi prestao da radi"],
    "psu.quiz.q3.a2": ["It erases the BIOS", "Briše BIOS"],
    "psu.quiz.q3.why": ["The big capacitor can hold about 400 V even after the PSU is unplugged.", "Veliki kondenzator može da drži oko 400 V i kad je napajanje isključeno iz struje."],
    "ui.test.eyebrow": ["Lab test", "Laboratorijski test"],
    "ui.test.title": ["Three hands-on tasks", "Tri praktična zadatka"],
    "ui.test.p": ["Put steps in order, match pairs and estimate a number. You start with 100 points; each mistake costs 10.", "Poređaj korake, upari parove i proceni broj. Počinješ sa 100 poena, a svaka greška košta 10."],
    "ui.test.order": ["Order", "Poređaj"],
    "ui.test.match": ["Match", "Upari"],
    "ui.test.estimate": ["Estimate", "Proceni"],
    "ui.test.points": ["Score {n}", "Rezultat {n}"],
    "ui.test.intro": ["Three short tasks about this part. Take your time: only mistakes cost points.", "Tri kratka zadatka o ovom delu. Ne žuri: poene gubiš samo na greškama."],
    "ui.test.start": ["Start the test", "Započni test"],
    "ui.test.orderHint": ["Tap the items in the right order.", "Dodiruj stavke pravim redom."],
    "ui.test.matchHint": ["Tap an item on the left, then its pair on the right.", "Dodirni stavku levo, pa njen par desno."],
    "ui.test.check": ["Check", "Proveri"],
    "ui.test.right": ["Correct!", "Tačno!"],
    "ui.test.wrong": ["Not that one. Try again.", "Nije to. Probaj ponovo."],
    "ui.test.high": ["Too high. Try lower.", "Previše. Probaj manje."],
    "ui.test.low": ["Too low. Try higher.", "Premalo. Probaj više."],
    "ui.test.next": ["Next task", "Sledeći zadatak"],
    "ui.test.finish": ["See my score", "Pogledaj rezultat"],
    "ui.test.g1": ["Worth another look", "Vredi pogledati ponovo"],
    "ui.test.g2": ["Solid work", "Dobar rad"],
    "ui.test.g3": ["Excellent", "Odlično"],
    "ui.test.summary": ["{s} out of 100 · mistakes: {m}", "{s} od 100 · grešaka: {m}"],
    "ui.test.again": ["Try again", "Pokušaj ponovo"],
    "ui.test.slider": ["Your estimate", "Tvoja procena"],

    "cpu.test.o.q": ["Put the steps a core takes for one instruction in order.", "Poređaj korake kojima jezgro izvršava jednu instrukciju."],
    "cpu.test.o.i0": ["Fetch", "Dohvatanje"],
    "cpu.test.o.i1": ["Decode", "Dekodiranje"],
    "cpu.test.o.i2": ["Execute", "Izvršavanje"],
    "cpu.test.o.i3": ["Write the result", "Upis rezultata"],
    "cpu.test.o.why": ["Every instruction is fetched, decoded, executed, and its result written back.", "Svaka instrukcija se dohvati, dekodira, izvrši, pa se njen rezultat upiše."],
    "cpu.test.m.q": ["Match each place the core reads data from with how long it waits.", "Upari svako mesto odakle jezgro čita podatke sa vremenom čekanja."],
    "cpu.test.m.a0": ["Registers", "Registri"],
    "cpu.test.m.a1": ["L1 cache", "L1 keš"],
    "cpu.test.m.a2": ["L3 cache", "L3 keš"],
    "cpu.test.m.a3": ["RAM", "RAM"],
    "cpu.test.m.b0": ["1 cycle", "1 ciklus"],
    "cpu.test.m.b1": ["~5 cycles", "~5 ciklusa"],
    "cpu.test.m.b2": ["~50 cycles", "~50 ciklusa"],
    "cpu.test.m.b3": ["~400 cycles", "~400 ciklusa"],
    "cpu.test.m.why": ["The farther data sits from the core, the longer the wait. That is why caches exist.", "Što je podatak dalje od jezgra, čekanje je duže. Zato postoje keševi."],
    "cpu.test.e.q": ["A 5 GHz clock ticks how many times in one nanosecond?", "Koliko puta takt od 5 GHz otkuca za jednu nanosekundu?"],
    "cpu.test.e.unit": ["ticks", "otkucaja"],
    "cpu.test.e.why": ["5 GHz is 5 billion ticks per second, and a nanosecond is a billionth of a second.", "5 GHz je 5 milijardi otkucaja u sekundi, a nanosekunda je milijarditi deo sekunde."],

    "gpu.test.o.q": ["Put the steps of drawing a 3D frame in order.", "Poređaj korake crtanja 3D slike."],
    "gpu.test.o.i0": ["Place the vertices", "Postavljanje temena"],
    "gpu.test.o.i1": ["Build triangles", "Sklapanje trouglova"],
    "gpu.test.o.i2": ["Rasterise into pixels", "Rasterizacija u piksele"],
    "gpu.test.o.i3": ["Shade the pixels", "Senčenje piksela"],
    "gpu.test.o.why": ["Points become triangles, triangles become pixels, and every pixel gets its colour.", "Tačke postaju trouglovi, trouglovi postaju pikseli, a svaki piksel dobija boju."],
    "gpu.test.m.q": ["Match each frame rate with the time the GPU has for one frame.", "Upari svaki broj slika u sekundi sa vremenom koje GPU ima za jednu sliku."],
    "gpu.test.m.a0": ["30 FPS", "30 FPS"],
    "gpu.test.m.a1": ["60 FPS", "60 FPS"],
    "gpu.test.m.a2": ["144 FPS", "144 FPS"],
    "gpu.test.m.a3": ["240 FPS", "240 FPS"],
    "gpu.test.m.b0": ["33.3 ms", "33,3 ms"],
    "gpu.test.m.b1": ["16.7 ms", "16,7 ms"],
    "gpu.test.m.b2": ["6.9 ms", "6,9 ms"],
    "gpu.test.m.b3": ["4.2 ms", "4,2 ms"],
    "gpu.test.m.why": ["Time per frame is 1,000 ms divided by the frame rate.", "Vreme za jednu sliku je 1.000 ms podeljeno brojem slika u sekundi."],
    "gpu.test.e.q": ["How many pixels does a 1920 × 1080 screen have?", "Koliko piksela ima ekran 1920 × 1080?"],
    "gpu.test.e.unit": ["million", "miliona"],
    "gpu.test.e.why": ["1920 × 1080 = 2,073,600, about 2.1 million pixels, shaded again for every frame.", "1920 × 1080 = 2.073.600, oko 2,1 milion piksela, koji se senče iznova za svaku sliku."],

    "ram.test.o.q": ["Put the steps of reading from DRAM in order.", "Poređaj korake čitanja iz DRAM-a."],
    "ram.test.o.i0": ["Open the row", "Otvaranje reda"],
    "ram.test.o.i1": ["Pick the column", "Biranje kolone"],
    "ram.test.o.i2": ["Send the data out", "Slanje podataka"],
    "ram.test.o.i3": ["Close the row", "Zatvaranje reda"],
    "ram.test.o.why": ["A whole row is opened first, then the column picks the bits, and the row is closed so another can open.", "Prvo se otvori ceo red, kolona izabere bitove, pa se red zatvori da bi mogao da se otvori drugi."],
    "ram.test.m.q": ["Match each DDR generation with a typical speed.", "Upari svaku DDR generaciju sa uobičajenom brzinom."],
    "ram.test.m.a0": ["DDR2", "DDR2"],
    "ram.test.m.a1": ["DDR3", "DDR3"],
    "ram.test.m.a2": ["DDR4", "DDR4"],
    "ram.test.m.a3": ["DDR5", "DDR5"],
    "ram.test.m.b0": ["800 MT/s", "800 MT/s"],
    "ram.test.m.b1": ["1600 MT/s", "1600 MT/s"],
    "ram.test.m.b2": ["3200 MT/s", "3200 MT/s"],
    "ram.test.m.b3": ["6000 MT/s", "6000 MT/s"],
    "ram.test.m.why": ["Each generation roughly doubled the number of transfers per second.", "Svaka generacija je otprilike udvostručila broj prenosa u sekundi."],
    "ram.test.e.q": ["DDR5-6000 moves 8 bytes per transfer. How many GB/s is that?", "DDR5-6000 prenosi 8 bajtova po prenosu. Koliko je to GB/s?"],
    "ram.test.e.unit": ["GB/s", "GB/s"],
    "ram.test.e.why": ["6,000 million transfers × 8 bytes = 48,000 MB/s, or 48 GB/s per stick.", "6.000 miliona prenosa × 8 bajtova = 48.000 MB/s, odnosno 48 GB/s po modulu."],

    "sto.test.o.q": ["Order these from fastest to slowest at reading a big file.", "Poređaj ih od najbržeg do najsporijeg pri čitanju velike datoteke."],
    "sto.test.o.i0": ["NVMe SSD (PCIe 4.0)", "NVMe SSD (PCIe 4.0)"],
    "sto.test.o.i1": ["SATA SSD", "SATA SSD"],
    "sto.test.o.i2": ["Hard drive", "Hard disk"],
    "sto.test.o.i3": ["USB 2.0 flash drive", "USB 2.0 fleš"],
    "sto.test.o.why": ["Roughly 7,000, 550, 200 and 35 MB/s.", "Otprilike 7.000, 550, 200 i 35 MB/s."],
    "sto.test.m.q": ["Match each flash cell type with the bits it stores.", "Upari svaki tip fleš ćelije sa brojem bitova koje čuva."],
    "sto.test.m.a0": ["SLC", "SLC"],
    "sto.test.m.a1": ["MLC", "MLC"],
    "sto.test.m.a2": ["TLC", "TLC"],
    "sto.test.m.a3": ["QLC", "QLC"],
    "sto.test.m.b0": ["1 bit", "1 bit"],
    "sto.test.m.b1": ["2 bits", "2 bita"],
    "sto.test.m.b2": ["3 bits", "3 bita"],
    "sto.test.m.b3": ["4 bits", "4 bita"],
    "sto.test.m.why": ["More bits per cell means more space, but slower writes and a shorter life.", "Više bitova po ćeliji znači više prostora, ali sporiji upis i kraći vek."],
    "sto.test.e.q": ["A hard drive spins at 7,200 rpm. How many turns is that per second?", "Hard disk se okreće 7.200 obrtaja u minuti. Koliko je to obrtaja u sekundi?"],
    "sto.test.e.unit": ["turns/s", "obrtaja/s"],
    "sto.test.e.why": ["7,200 ÷ 60 = 120 turns every second.", "7.200 ÷ 60 = 120 obrtaja svake sekunde."],

    "mb.test.o.q": ["Put the path of a key press in order.", "Poređaj put pritiska tastera."],
    "mb.test.o.i0": ["Key on the keyboard", "Taster na tastaturi"],
    "mb.test.o.i1": ["USB port", "USB port"],
    "mb.test.o.i2": ["Chipset", "Čipset"],
    "mb.test.o.i3": ["CPU", "Procesor"],
    "mb.test.o.why": ["Most USB ports hang off the chipset, which talks to the CPU over its own link.", "Većina USB portova je povezana na čipset, koji sa procesorom razgovara preko svoje veze."],
    "mb.test.m.q": ["Match each slot or connector with what plugs into it.", "Upari svaki slot ili konektor sa onim što se u njega uključuje."],
    "mb.test.m.a0": ["DIMM slot", "DIMM slot"],
    "mb.test.m.a1": ["PCIe x16 slot", "PCIe x16 slot"],
    "mb.test.m.a2": ["M.2 slot", "M.2 slot"],
    "mb.test.m.a3": ["24-pin ATX", "24-pinski ATX"],
    "mb.test.m.b0": ["RAM stick", "RAM modul"],
    "mb.test.m.b1": ["Graphics card", "Grafička karta"],
    "mb.test.m.b2": ["SSD", "SSD"],
    "mb.test.m.b3": ["PSU cable", "Kabl napajanja"],
    "mb.test.m.why": ["Every slot has its own shape and key, so only the right part fits.", "Svaki slot ima svoj oblik i zarez, pa u njega ulazi samo pravi deo."],
    "mb.test.e.q": ["A PCIe 4.0 lane carries about 2 GB/s. How much does an x16 slot carry?", "Jedna PCIe 4.0 linija prenosi oko 2 GB/s. Koliko prenosi x16 slot?"],
    "mb.test.e.unit": ["GB/s", "GB/s"],
    "mb.test.e.why": ["16 lanes × 2 GB/s = 32 GB/s in each direction.", "16 linija × 2 GB/s = 32 GB/s u svakom smeru."],

    "psu.test.o.q": ["Put the stages inside a PSU in order, from the wall to the PC.", "Poređaj faze unutar napajanja, od utičnice do računara."],
    "psu.test.o.i0": ["Rectify", "Ispravljanje"],
    "psu.test.o.i1": ["Smooth", "Izravnavanje"],
    "psu.test.o.i2": ["Chop", "Seckanje"],
    "psu.test.o.i3": ["Transform", "Transformacija"],
    "psu.test.o.i4": ["Clean 12 V", "Čistih 12 V"],
    "psu.test.o.why": ["AC is flipped to one direction, smoothed to ~400 V, chopped into pulses, stepped down and filtered to 12 V.", "Naizmenična struja se okrene u jedan smer, izravna na ~400 V, iseče na impulse, spusti i filtrira na 12 V."],
    "psu.test.m.q": ["Match each cable with what it powers.", "Upari svaki kabl sa onim što napaja."],
    "psu.test.m.a0": ["24-pin ATX", "24-pinski ATX"],
    "psu.test.m.a1": ["8-pin EPS", "8-pinski EPS"],
    "psu.test.m.a2": ["12V-2x6", "12V-2x6"],
    "psu.test.m.a3": ["SATA power", "SATA napajanje"],
    "psu.test.m.b0": ["Motherboard", "Matična ploča"],
    "psu.test.m.b1": ["CPU", "Procesor"],
    "psu.test.m.b2": ["Graphics card", "Grafička karta"],
    "psu.test.m.b3": ["Drives", "Diskovi"],
    "psu.test.m.why": ["The CPU and graphics card get their own thick 12 V cables because they draw the most power.", "Procesor i grafička karta dobijaju svoje debele kablove od 12 V jer troše najviše struje."],
    "psu.test.e.q": ["A PC draws 540 W from a 90% efficient PSU. How much does the PSU take from the wall?", "Računar uzima 540 W iz napajanja od 90% efikasnosti. Koliko napajanje uzima iz utičnice?"],
    "psu.test.e.unit": ["W", "W"],
    "psu.test.e.why": ["540 ÷ 0.9 = 600 W. The extra 60 W turns into heat.", "540 ÷ 0,9 = 600 W. Višak od 60 W postaje toplota."]
  });
})();
